const EXAMPLES = [
  {
    "id": 1,
    "name": "Approved Profile 1",
    "description": "Strong credit, DTI 31%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 160,
      "income_range": "$50,000-74,999",
      "monthly_income": 6888.0,
      "is_homeowner": true,
      "state": "IL",
      "in_group": true,
      "credit_score_lower": 765,
      "credit_score_upper": 784,
      "debt_to_income": 0.32,
      "current_credit_lines": 13,
      "revolving_balance": 1915.0,
      "bankcard_utilization": 0.27,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 18000.0,
      "term": 36,
      "listing_category": 4,
      "lender_yield": 0.0679,
      "monthly_payment": 550.0,
      "total_inquiries": 2,
      "inquiries_6m": 0,
      "total_trades": 27,
      "trades_never_delinquent": 100.0,
      "available_credit": 68165.0,
      "investors": 3,
      "investment_friends_amount": 0.0,
      "recommendations": 1
    },
    "prediction": {
      "approved": true,
      "probability": 0.9966666666666667
    },
    "category": "good"
  },
  {
    "id": 2,
    "name": "Approved Profile 2",
    "description": "Strong credit, DTI 24%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 90,
      "income_range": "$100,000+",
      "monthly_income": 10228.0,
      "is_homeowner": true,
      "state": "IL",
      "in_group": true,
      "credit_score_lower": 742,
      "credit_score_upper": 761,
      "debt_to_income": 0.25,
      "current_credit_lines": 10,
      "revolving_balance": 8144.0,
      "bankcard_utilization": 0.25,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 24000.0,
      "term": 60,
      "listing_category": 3,
      "lender_yield": 0.0622,
      "monthly_payment": 733.33,
      "total_inquiries": 2,
      "inquiries_6m": 0,
      "total_trades": 24,
      "trades_never_delinquent": 100.0,
      "available_credit": 26847.0,
      "investors": 13,
      "investment_friends_amount": 0.0,
      "recommendations": 2
    },
    "prediction": {
      "approved": true,
      "probability": 0.9899999999999999
    },
    "category": "good"
  },
  {
    "id": 3,
    "name": "Approved Profile 3",
    "description": "Strong credit, DTI 31%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 41,
      "income_range": "$50,000-74,999",
      "monthly_income": 7498.0,
      "is_homeowner": true,
      "state": "WA",
      "in_group": false,
      "credit_score_lower": 766,
      "credit_score_upper": 785,
      "debt_to_income": 0.31,
      "current_credit_lines": 14,
      "revolving_balance": 4295.0,
      "bankcard_utilization": 0.08,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 16000.0,
      "term": 60,
      "listing_category": 4,
      "lender_yield": 0.118,
      "monthly_payment": 488.89,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 17,
      "trades_never_delinquent": 100.0,
      "available_credit": 43943.0,
      "investors": 4,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 0.9938888888888888
    },
    "category": "good"
  },
  {
    "id": 4,
    "name": "Approved Profile 4",
    "description": "Strong credit, DTI 21%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 160,
      "income_range": "$50,000-74,999",
      "monthly_income": 5579.0,
      "is_homeowner": true,
      "state": "WA",
      "in_group": false,
      "credit_score_lower": 792,
      "credit_score_upper": 811,
      "debt_to_income": 0.22,
      "current_credit_lines": 12,
      "revolving_balance": 3671.0,
      "bankcard_utilization": 0.12,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 27000.0,
      "term": 60,
      "listing_category": 4,
      "lender_yield": 0.0893,
      "monthly_payment": 825.0,
      "total_inquiries": 2,
      "inquiries_6m": 0,
      "total_trades": 23,
      "trades_never_delinquent": 100.0,
      "available_credit": 50840.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 2
    },
    "prediction": {
      "approved": true,
      "probability": 0.9466666666666667
    },
    "category": "good"
  },
  {
    "id": 5,
    "name": "Approved Profile 5",
    "description": "Strong credit, DTI 12%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 133,
      "income_range": "$100,000+",
      "monthly_income": 11967.0,
      "is_homeowner": true,
      "state": "FL",
      "in_group": false,
      "credit_score_lower": 795,
      "credit_score_upper": 814,
      "debt_to_income": 0.12,
      "current_credit_lines": 5,
      "revolving_balance": 1574.0,
      "bankcard_utilization": 0.05,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 38000.0,
      "term": 60,
      "listing_category": 2,
      "lender_yield": 0.0625,
      "monthly_payment": 1161.11,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 13,
      "trades_never_delinquent": 100.0,
      "available_credit": 73871.0,
      "investors": 30,
      "investment_friends_amount": 0.0,
      "recommendations": 2
    },
    "prediction": {
      "approved": true,
      "probability": 1.0
    },
    "category": "good"
  },
  {
    "id": 6,
    "name": "Approved Profile 6",
    "description": "Strong credit, DTI 16%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 50,
      "income_range": "$100,000+",
      "monthly_income": 10733.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": false,
      "credit_score_lower": 758,
      "credit_score_upper": 777,
      "debt_to_income": 0.17,
      "current_credit_lines": 7,
      "revolving_balance": 6448.0,
      "bankcard_utilization": 0.13,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 32000.0,
      "term": 36,
      "listing_category": 2,
      "lender_yield": 0.0729,
      "monthly_payment": 977.78,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 19,
      "trades_never_delinquent": 100.0,
      "available_credit": 29481.0,
      "investors": 40,
      "investment_friends_amount": 0.0,
      "recommendations": 1
    },
    "prediction": {
      "approved": true,
      "probability": 1.0
    },
    "category": "good"
  },
  {
    "id": 7,
    "name": "Approved Profile 7",
    "description": "Strong credit, DTI 15%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 128,
      "income_range": "$50,000-74,999",
      "monthly_income": 8311.0,
      "is_homeowner": true,
      "state": "CA",
      "in_group": false,
      "credit_score_lower": 726,
      "credit_score_upper": 745,
      "debt_to_income": 0.15,
      "current_credit_lines": 9,
      "revolving_balance": 9858.0,
      "bankcard_utilization": 0.25,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 18000.0,
      "term": 60,
      "listing_category": 4,
      "lender_yield": 0.0993,
      "monthly_payment": 550.0,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 22,
      "trades_never_delinquent": 100.0,
      "available_credit": 71644.0,
      "investors": 4,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 0.9899999999999999
    },
    "category": "good"
  },
  {
    "id": 8,
    "name": "Approved Profile 8",
    "description": "Strong credit, DTI 34%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 164,
      "income_range": "$100,000+",
      "monthly_income": 10388.0,
      "is_homeowner": true,
      "state": "WA",
      "in_group": true,
      "credit_score_lower": 717,
      "credit_score_upper": 736,
      "debt_to_income": 0.35,
      "current_credit_lines": 7,
      "revolving_balance": 9456.0,
      "bankcard_utilization": 0.13,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 16000.0,
      "term": 36,
      "listing_category": 7,
      "lender_yield": 0.086,
      "monthly_payment": 488.89,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 20,
      "trades_never_delinquent": 100.0,
      "available_credit": 83925.0,
      "investors": 7,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 0.9866666666666667
    },
    "category": "good"
  },
  {
    "id": 9,
    "name": "Approved Profile 9",
    "description": "Strong credit, DTI 16%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 49,
      "income_range": "$50,000-74,999",
      "monthly_income": 7737.0,
      "is_homeowner": true,
      "state": "WA",
      "in_group": false,
      "credit_score_lower": 751,
      "credit_score_upper": 770,
      "debt_to_income": 0.17,
      "current_credit_lines": 12,
      "revolving_balance": 1087.0,
      "bankcard_utilization": 0.27,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 17000.0,
      "term": 60,
      "listing_category": 1,
      "lender_yield": 0.1159,
      "monthly_payment": 519.44,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 23,
      "trades_never_delinquent": 100.0,
      "available_credit": 53002.0,
      "investors": 44,
      "investment_friends_amount": 0.0,
      "recommendations": 1
    },
    "prediction": {
      "approved": true,
      "probability": 1.0
    },
    "category": "good"
  },
  {
    "id": 10,
    "name": "Approved Profile 10",
    "description": "Strong credit, DTI 17%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 118,
      "income_range": "$50,000-74,999",
      "monthly_income": 5566.0,
      "is_homeowner": true,
      "state": "AZ",
      "in_group": false,
      "credit_score_lower": 722,
      "credit_score_upper": 741,
      "debt_to_income": 0.17,
      "current_credit_lines": 10,
      "revolving_balance": 6048.0,
      "bankcard_utilization": 0.22,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 26000.0,
      "term": 36,
      "listing_category": 1,
      "lender_yield": 0.1139,
      "monthly_payment": 794.44,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 30,
      "trades_never_delinquent": 100.0,
      "available_credit": 72135.0,
      "investors": 29,
      "investment_friends_amount": 0.0,
      "recommendations": 1
    },
    "prediction": {
      "approved": true,
      "probability": 0.9966666666666667
    },
    "category": "good"
  },
  {
    "id": 11,
    "name": "Approved Profile 11",
    "description": "Strong credit, DTI 17%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 137,
      "income_range": "$100,000+",
      "monthly_income": 13469.0,
      "is_homeowner": true,
      "state": "TX",
      "in_group": true,
      "credit_score_lower": 709,
      "credit_score_upper": 728,
      "debt_to_income": 0.17,
      "current_credit_lines": 7,
      "revolving_balance": 1625.0,
      "bankcard_utilization": 0.1,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 17000.0,
      "term": 36,
      "listing_category": 2,
      "lender_yield": 0.0898,
      "monthly_payment": 519.44,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 15,
      "trades_never_delinquent": 100.0,
      "available_credit": 33104.0,
      "investors": 4,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 0.9866666666666667
    },
    "category": "good"
  },
  {
    "id": 12,
    "name": "Approved Profile 12",
    "description": "Strong credit, DTI 10%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 36,
      "income_range": "$100,000+",
      "monthly_income": 11196.0,
      "is_homeowner": true,
      "state": "CA",
      "in_group": false,
      "credit_score_lower": 712,
      "credit_score_upper": 731,
      "debt_to_income": 0.1,
      "current_credit_lines": 15,
      "revolving_balance": 4881.0,
      "bankcard_utilization": 0.14,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 5000.0,
      "term": 60,
      "listing_category": 2,
      "lender_yield": 0.0507,
      "monthly_payment": 152.78,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 25,
      "trades_never_delinquent": 100.0,
      "available_credit": 71260.0,
      "investors": 27,
      "investment_friends_amount": 0.0,
      "recommendations": 2
    },
    "prediction": {
      "approved": true,
      "probability": 0.9966666666666667
    },
    "category": "good"
  },
  {
    "id": 13,
    "name": "Approved Profile 13",
    "description": "Strong credit, DTI 27%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 101,
      "income_range": "$100,000+",
      "monthly_income": 12736.0,
      "is_homeowner": true,
      "state": "TX",
      "in_group": false,
      "credit_score_lower": 732,
      "credit_score_upper": 751,
      "debt_to_income": 0.28,
      "current_credit_lines": 12,
      "revolving_balance": 2709.0,
      "bankcard_utilization": 0.23,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 40000.0,
      "term": 36,
      "listing_category": 2,
      "lender_yield": 0.0863,
      "monthly_payment": 1222.22,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 13,
      "trades_never_delinquent": 100.0,
      "available_credit": 69542.0,
      "investors": 42,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 1.0
    },
    "category": "good"
  },
  {
    "id": 14,
    "name": "Approved Profile 14",
    "description": "Strong credit, DTI 21%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 79,
      "income_range": "$100,000+",
      "monthly_income": 8398.0,
      "is_homeowner": true,
      "state": "AZ",
      "in_group": true,
      "credit_score_lower": 774,
      "credit_score_upper": 793,
      "debt_to_income": 0.21,
      "current_credit_lines": 12,
      "revolving_balance": 8245.0,
      "bankcard_utilization": 0.22,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 6000.0,
      "term": 36,
      "listing_category": 5,
      "lender_yield": 0.0874,
      "monthly_payment": 183.33,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 29,
      "trades_never_delinquent": 100.0,
      "available_credit": 21932.0,
      "investors": 41,
      "investment_friends_amount": 0.0,
      "recommendations": 1
    },
    "prediction": {
      "approved": true,
      "probability": 0.9899999999999999
    },
    "category": "good"
  },
  {
    "id": 15,
    "name": "Approved Profile 15",
    "description": "Strong credit, DTI 28%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 61,
      "income_range": "$50,000-74,999",
      "monthly_income": 6563.0,
      "is_homeowner": true,
      "state": "TX",
      "in_group": false,
      "credit_score_lower": 734,
      "credit_score_upper": 753,
      "debt_to_income": 0.28,
      "current_credit_lines": 15,
      "revolving_balance": 2903.0,
      "bankcard_utilization": 0.18,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 32000.0,
      "term": 36,
      "listing_category": 7,
      "lender_yield": 0.0533,
      "monthly_payment": 977.78,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 21,
      "trades_never_delinquent": 100.0,
      "available_credit": 91473.0,
      "investors": 35,
      "investment_friends_amount": 0.0,
      "recommendations": 1
    },
    "prediction": {
      "approved": true,
      "probability": 0.9966666666666667
    },
    "category": "good"
  },
  {
    "id": 16,
    "name": "Approved Profile 16",
    "description": "Strong credit, DTI 34%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 41,
      "income_range": "$50,000-74,999",
      "monthly_income": 7217.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": true,
      "credit_score_lower": 708,
      "credit_score_upper": 727,
      "debt_to_income": 0.35,
      "current_credit_lines": 5,
      "revolving_balance": 4523.0,
      "bankcard_utilization": 0.1,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 23000.0,
      "term": 36,
      "listing_category": 7,
      "lender_yield": 0.0833,
      "monthly_payment": 702.78,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 17,
      "trades_never_delinquent": 100.0,
      "available_credit": 90806.0,
      "investors": 2,
      "investment_friends_amount": 0.0,
      "recommendations": 2
    },
    "prediction": {
      "approved": true,
      "probability": 0.9266666666666667
    },
    "category": "good"
  },
  {
    "id": 17,
    "name": "Approved Profile 17",
    "description": "Strong credit, DTI 19%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 58,
      "income_range": "$100,000+",
      "monthly_income": 11775.0,
      "is_homeowner": true,
      "state": "CA",
      "in_group": true,
      "credit_score_lower": 791,
      "credit_score_upper": 810,
      "debt_to_income": 0.2,
      "current_credit_lines": 10,
      "revolving_balance": 4743.0,
      "bankcard_utilization": 0.12,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 19000.0,
      "term": 60,
      "listing_category": 5,
      "lender_yield": 0.1193,
      "monthly_payment": 580.56,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 15,
      "trades_never_delinquent": 100.0,
      "available_credit": 24111.0,
      "investors": 39,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 0.9938888888888888
    },
    "category": "good"
  },
  {
    "id": 18,
    "name": "Approved Profile 18",
    "description": "Strong credit, DTI 25%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 41,
      "income_range": "$50,000-74,999",
      "monthly_income": 5968.0,
      "is_homeowner": true,
      "state": "TX",
      "in_group": true,
      "credit_score_lower": 748,
      "credit_score_upper": 767,
      "debt_to_income": 0.25,
      "current_credit_lines": 13,
      "revolving_balance": 9048.0,
      "bankcard_utilization": 0.09,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 33000.0,
      "term": 36,
      "listing_category": 5,
      "lender_yield": 0.0558,
      "monthly_payment": 1008.33,
      "total_inquiries": 2,
      "inquiries_6m": 0,
      "total_trades": 37,
      "trades_never_delinquent": 100.0,
      "available_credit": 96838.0,
      "investors": 50,
      "investment_friends_amount": 0.0,
      "recommendations": 2
    },
    "prediction": {
      "approved": true,
      "probability": 0.9966666666666667
    },
    "category": "good"
  },
  {
    "id": 19,
    "name": "Approved Profile 19",
    "description": "Strong credit, DTI 20%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 46,
      "income_range": "$50,000-74,999",
      "monthly_income": 5247.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": false,
      "credit_score_lower": 765,
      "credit_score_upper": 784,
      "debt_to_income": 0.2,
      "current_credit_lines": 5,
      "revolving_balance": 2178.0,
      "bankcard_utilization": 0.07,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 38000.0,
      "term": 36,
      "listing_category": 1,
      "lender_yield": 0.0805,
      "monthly_payment": 1161.11,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 39,
      "trades_never_delinquent": 100.0,
      "available_credit": 82693.0,
      "investors": 29,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 0.9822222222222221
    },
    "category": "good"
  },
  {
    "id": 20,
    "name": "Approved Profile 20",
    "description": "Strong credit, DTI 25%, stable income",
    "tags": [
      "low-risk",
      "approved-likely"
    ],
    "loan_status": 0,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 79,
      "income_range": "$50,000-74,999",
      "monthly_income": 7308.0,
      "is_homeowner": true,
      "state": "WA",
      "in_group": false,
      "credit_score_lower": 707,
      "credit_score_upper": 726,
      "debt_to_income": 0.25,
      "current_credit_lines": 15,
      "revolving_balance": 1667.0,
      "bankcard_utilization": 0.25,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 16000.0,
      "term": 60,
      "listing_category": 6,
      "lender_yield": 0.0526,
      "monthly_payment": 488.89,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 19,
      "trades_never_delinquent": 100.0,
      "available_credit": 60520.0,
      "investors": 39,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": true,
      "probability": 0.9205555555555556
    },
    "category": "good"
  },
  {
    "id": 21,
    "name": "Near-Approval Loan 1",
    "description": "Rejected initially but has alternatives.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 30,
      "income_range": "$50,000-74,999",
      "monthly_income": 3216.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": true,
      "credit_score_lower": 646,
      "credit_score_upper": 665,
      "debt_to_income": 0.4,
      "current_credit_lines": 13,
      "revolving_balance": 5365.0,
      "bankcard_utilization": 0.58,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 31000.0,
      "term": 60,
      "listing_category": 3,
      "lender_yield": 0.2282,
      "monthly_payment": 671.67,
      "total_inquiries": 5,
      "inquiries_6m": 0,
      "total_trades": 18,
      "trades_never_delinquent": 100.0,
      "available_credit": 8921.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.07888888888888888
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 22,
    "name": "Near-Approval Loan 2",
    "description": "Rejected initially but has alternatives.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 52,
      "income_range": "$50,000-74,999",
      "monthly_income": 3332.0,
      "is_homeowner": false,
      "state": "FL",
      "in_group": true,
      "credit_score_lower": 669,
      "credit_score_upper": 688,
      "debt_to_income": 0.5,
      "current_credit_lines": 9,
      "revolving_balance": 11016.0,
      "bankcard_utilization": 0.77,
      "delinquencies_7y": 1,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 31000.0,
      "term": 60,
      "listing_category": 1,
      "lender_yield": 0.1614,
      "monthly_payment": 671.67,
      "total_inquiries": 4,
      "inquiries_6m": 0,
      "total_trades": 20,
      "trades_never_delinquent": 92.0,
      "available_credit": 1035.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.02388888888888889
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 23,
    "name": "Near-Approval Loan 3",
    "description": "Rejected initially but has alternatives.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 80,
      "income_range": "$50,000-74,999",
      "monthly_income": 5602.0,
      "is_homeowner": false,
      "state": "FL",
      "in_group": false,
      "credit_score_lower": 656,
      "credit_score_upper": 675,
      "debt_to_income": 0.41,
      "current_credit_lines": 11,
      "revolving_balance": 14676.0,
      "bankcard_utilization": 0.89,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 32000.0,
      "term": 60,
      "listing_category": 1,
      "lender_yield": 0.1532,
      "monthly_payment": 693.33,
      "total_inquiries": 1,
      "inquiries_6m": 1,
      "total_trades": 17,
      "trades_never_delinquent": 81.0,
      "available_credit": 4243.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.08722222222222221
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 24,
    "name": "Near-Approval Loan 4",
    "description": "Rejected initially but has alternatives.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 32,
      "income_range": "$50,000-74,999",
      "monthly_income": 4299.0,
      "is_homeowner": false,
      "state": "TX",
      "in_group": false,
      "credit_score_lower": 707,
      "credit_score_upper": 726,
      "debt_to_income": 0.5,
      "current_credit_lines": 12,
      "revolving_balance": 5508.0,
      "bankcard_utilization": 0.66,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 23000.0,
      "term": 60,
      "listing_category": 7,
      "lender_yield": 0.2313,
      "monthly_payment": 498.33,
      "total_inquiries": 2,
      "inquiries_6m": 2,
      "total_trades": 18,
      "trades_never_delinquent": 93.0,
      "available_credit": 4025.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.10722222222222222
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 25,
    "name": "Near-Approval Loan 5",
    "description": "Rejected initially but has alternatives.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Self-employed",
      "employment_duration": 72,
      "income_range": "$50,000-74,999",
      "monthly_income": 3258.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": true,
      "credit_score_lower": 696,
      "credit_score_upper": 715,
      "debt_to_income": 0.49,
      "current_credit_lines": 12,
      "revolving_balance": 18508.0,
      "bankcard_utilization": 0.85,
      "delinquencies_7y": 1,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 16000.0,
      "term": 60,
      "listing_category": 7,
      "lender_yield": 0.1958,
      "monthly_payment": 346.67,
      "total_inquiries": 1,
      "inquiries_6m": 2,
      "total_trades": 24,
      "trades_never_delinquent": 81.0,
      "available_credit": 8210.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.033888888888888885
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 26,
    "name": "High Risk Profile 1",
    "description": "High DTI 67%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Not employed",
      "employment_duration": 57,
      "income_range": "$25,000-49,999",
      "monthly_income": 2034.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": false,
      "credit_score_lower": 626,
      "credit_score_upper": 645,
      "debt_to_income": 0.68,
      "current_credit_lines": 9,
      "revolving_balance": 6228.0,
      "bankcard_utilization": 0.83,
      "delinquencies_7y": 6,
      "amount_delinquent": 4703.0,
      "public_records": 1,
      "loan_amount": 30000.0,
      "term": 60,
      "listing_category": 7,
      "lender_yield": 0.3224,
      "monthly_payment": 650.0,
      "total_inquiries": 15,
      "inquiries_6m": 5,
      "total_trades": 19,
      "trades_never_delinquent": 80.45999749026888,
      "available_credit": 969.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 27,
    "name": "High Risk Profile 2",
    "description": "High DTI 73%, low score",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 53,
      "income_range": "$25,000-49,999",
      "monthly_income": 4748.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": false,
      "credit_score_lower": 650,
      "credit_score_upper": 669,
      "debt_to_income": 0.74,
      "current_credit_lines": 4,
      "revolving_balance": 7603.0,
      "bankcard_utilization": 0.77,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 13000.0,
      "term": 60,
      "listing_category": 2,
      "lender_yield": 0.228,
      "monthly_payment": 281.67,
      "total_inquiries": 11,
      "inquiries_6m": 6,
      "total_trades": 9,
      "trades_never_delinquent": 82.32655438799594,
      "available_credit": 1594.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.02722222222222222
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 28,
    "name": "High Risk Profile 3",
    "description": "High DTI 52%, low score",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 8,
      "income_range": "$25,000-49,999",
      "monthly_income": 4458.0,
      "is_homeowner": true,
      "state": "CA",
      "in_group": false,
      "credit_score_lower": 635,
      "credit_score_upper": 654,
      "debt_to_income": 0.52,
      "current_credit_lines": 3,
      "revolving_balance": 6130.0,
      "bankcard_utilization": 0.83,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "loan_amount": 33000.0,
      "term": 60,
      "listing_category": 3,
      "lender_yield": 0.256,
      "monthly_payment": 715.0,
      "total_inquiries": 13,
      "inquiries_6m": 3,
      "total_trades": 8,
      "trades_never_delinquent": 65.74583085072881,
      "available_credit": 624.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.003888888888888889
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 29,
    "name": "High Risk Profile 4",
    "description": "High DTI 74%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 30,
      "income_range": "$25,000-49,999",
      "monthly_income": 3895.0,
      "is_homeowner": true,
      "state": "OH",
      "in_group": false,
      "credit_score_lower": 556,
      "credit_score_upper": 575,
      "debt_to_income": 0.74,
      "current_credit_lines": 3,
      "revolving_balance": 16174.0,
      "bankcard_utilization": 0.85,
      "delinquencies_7y": 9,
      "amount_delinquent": 2501.0,
      "public_records": 1,
      "loan_amount": 15000.0,
      "term": 60,
      "listing_category": 6,
      "lender_yield": 0.2183,
      "monthly_payment": 325.0,
      "total_inquiries": 14,
      "inquiries_6m": 4,
      "total_trades": 7,
      "trades_never_delinquent": 54.83337636779022,
      "available_credit": 1148.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 30,
    "name": "High Risk Profile 5",
    "description": "High DTI 74%, low score",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Not employed",
      "employment_duration": 26,
      "income_range": "$25,000-49,999",
      "monthly_income": 4535.0,
      "is_homeowner": true,
      "state": "FL",
      "in_group": false,
      "credit_score_lower": 642,
      "credit_score_upper": 661,
      "debt_to_income": 0.74,
      "current_credit_lines": 5,
      "revolving_balance": 5766.0,
      "bankcard_utilization": 0.83,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 1,
      "loan_amount": 19000.0,
      "term": 60,
      "listing_category": 4,
      "lender_yield": 0.2426,
      "monthly_payment": 411.67,
      "total_inquiries": 7,
      "inquiries_6m": 5,
      "total_trades": 19,
      "trades_never_delinquent": 74.40281014635174,
      "available_credit": 1570.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 31,
    "name": "High Risk Profile 6",
    "description": "High DTI 68%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Not employed",
      "employment_duration": 20,
      "income_range": "$25,000-49,999",
      "monthly_income": 3070.0,
      "is_homeowner": true,
      "state": "NV",
      "in_group": false,
      "credit_score_lower": 596,
      "credit_score_upper": 615,
      "debt_to_income": 0.68,
      "current_credit_lines": 6,
      "revolving_balance": 8620.0,
      "bankcard_utilization": 0.71,
      "delinquencies_7y": 4,
      "amount_delinquent": 4043.0,
      "public_records": 0,
      "loan_amount": 26000.0,
      "term": 60,
      "listing_category": 3,
      "lender_yield": 0.2025,
      "monthly_payment": 563.33,
      "total_inquiries": 6,
      "inquiries_6m": 6,
      "total_trades": 14,
      "trades_never_delinquent": 83.57446883882939,
      "available_credit": 171.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 32,
    "name": "High Risk Profile 7",
    "description": "High DTI 78%, low score",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Part-time",
      "employment_duration": 12,
      "income_range": "$25,000-49,999",
      "monthly_income": 3553.0,
      "is_homeowner": true,
      "state": "OH",
      "in_group": false,
      "credit_score_lower": 590,
      "credit_score_upper": 609,
      "debt_to_income": 0.78,
      "current_credit_lines": 10,
      "revolving_balance": 16726.0,
      "bankcard_utilization": 0.79,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 2,
      "loan_amount": 29000.0,
      "term": 60,
      "listing_category": 1,
      "lender_yield": 0.2277,
      "monthly_payment": 628.33,
      "total_inquiries": 9,
      "inquiries_6m": 3,
      "total_trades": 15,
      "trades_never_delinquent": 57.641571044588936,
      "available_credit": 1885.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 33,
    "name": "High Risk Profile 8",
    "description": "High DTI 48%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 5,
      "income_range": "$25,000-49,999",
      "monthly_income": 2898.0,
      "is_homeowner": false,
      "state": "TX",
      "in_group": false,
      "credit_score_lower": 577,
      "credit_score_upper": 596,
      "debt_to_income": 0.48,
      "current_credit_lines": 8,
      "revolving_balance": 6081.0,
      "bankcard_utilization": 0.8,
      "delinquencies_7y": 6,
      "amount_delinquent": 4351.0,
      "public_records": 2,
      "loan_amount": 20000.0,
      "term": 60,
      "listing_category": 4,
      "lender_yield": 0.3135,
      "monthly_payment": 433.33,
      "total_inquiries": 5,
      "inquiries_6m": 2,
      "total_trades": 19,
      "trades_never_delinquent": 69.2245650351778,
      "available_credit": 285.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 34,
    "name": "High Risk Profile 9",
    "description": "High DTI 72%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 19,
      "income_range": "$25,000-49,999",
      "monthly_income": 2434.0,
      "is_homeowner": false,
      "state": "CA",
      "in_group": false,
      "credit_score_lower": 659,
      "credit_score_upper": 678,
      "debt_to_income": 0.72,
      "current_credit_lines": 6,
      "revolving_balance": 17018.0,
      "bankcard_utilization": 0.85,
      "delinquencies_7y": 4,
      "amount_delinquent": 1204.0,
      "public_records": 1,
      "loan_amount": 22000.0,
      "term": 60,
      "listing_category": 2,
      "lender_yield": 0.2643,
      "monthly_payment": 476.67,
      "total_inquiries": 5,
      "inquiries_6m": 5,
      "total_trades": 9,
      "trades_never_delinquent": 74.86724603404933,
      "available_credit": 1073.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 35,
    "name": "High Risk Profile 10",
    "description": "High DTI 51%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Part-time",
      "employment_duration": 5,
      "income_range": "$25,000-49,999",
      "monthly_income": 2125.0,
      "is_homeowner": true,
      "state": "OH",
      "in_group": false,
      "credit_score_lower": 636,
      "credit_score_upper": 655,
      "debt_to_income": 0.52,
      "current_credit_lines": 2,
      "revolving_balance": 15667.0,
      "bankcard_utilization": 0.72,
      "delinquencies_7y": 1,
      "amount_delinquent": 2584.0,
      "public_records": 0,
      "loan_amount": 28000.0,
      "term": 60,
      "listing_category": 2,
      "lender_yield": 0.2917,
      "monthly_payment": 606.67,
      "total_inquiries": 12,
      "inquiries_6m": 6,
      "total_trades": 6,
      "trades_never_delinquent": 53.34378885749328,
      "available_credit": 1045.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 36,
    "name": "High Risk Profile 11",
    "description": "High DTI 49%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Not employed",
      "employment_duration": 43,
      "income_range": "$25,000-49,999",
      "monthly_income": 4194.0,
      "is_homeowner": false,
      "state": "NV",
      "in_group": false,
      "credit_score_lower": 622,
      "credit_score_upper": 641,
      "debt_to_income": 0.5,
      "current_credit_lines": 8,
      "revolving_balance": 9098.0,
      "bankcard_utilization": 0.7,
      "delinquencies_7y": 3,
      "amount_delinquent": 2474.0,
      "public_records": 1,
      "loan_amount": 34000.0,
      "term": 60,
      "listing_category": 6,
      "lender_yield": 0.3378,
      "monthly_payment": 736.67,
      "total_inquiries": 9,
      "inquiries_6m": 2,
      "total_trades": 6,
      "trades_never_delinquent": 84.42574976251947,
      "available_credit": 25.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.003888888888888889
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 37,
    "name": "High Risk Profile 12",
    "description": "High DTI 59%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Part-time",
      "employment_duration": 22,
      "income_range": "$25,000-49,999",
      "monthly_income": 2710.0,
      "is_homeowner": false,
      "state": "TX",
      "in_group": false,
      "credit_score_lower": 613,
      "credit_score_upper": 632,
      "debt_to_income": 0.6,
      "current_credit_lines": 9,
      "revolving_balance": 14652.0,
      "bankcard_utilization": 0.87,
      "delinquencies_7y": 7,
      "amount_delinquent": 4531.0,
      "public_records": 2,
      "loan_amount": 10000.0,
      "term": 60,
      "listing_category": 7,
      "lender_yield": 0.2505,
      "monthly_payment": 216.67,
      "total_inquiries": 6,
      "inquiries_6m": 3,
      "total_trades": 16,
      "trades_never_delinquent": 61.87738610597712,
      "available_credit": 1671.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 38,
    "name": "High Risk Profile 13",
    "description": "High DTI 49%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Not employed",
      "employment_duration": 30,
      "income_range": "$25,000-49,999",
      "monthly_income": 2986.0,
      "is_homeowner": false,
      "state": "CA",
      "in_group": false,
      "credit_score_lower": 576,
      "credit_score_upper": 595,
      "debt_to_income": 0.49,
      "current_credit_lines": 9,
      "revolving_balance": 6792.0,
      "bankcard_utilization": 0.97,
      "delinquencies_7y": 4,
      "amount_delinquent": 2391.0,
      "public_records": 2,
      "loan_amount": 14000.0,
      "term": 60,
      "listing_category": 4,
      "lender_yield": 0.3114,
      "monthly_payment": 303.33,
      "total_inquiries": 14,
      "inquiries_6m": 5,
      "total_trades": 17,
      "trades_never_delinquent": 83.01397373219258,
      "available_credit": 157.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 39,
    "name": "High Risk Profile 14",
    "description": "High DTI 53%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Not employed",
      "employment_duration": 52,
      "income_range": "$25,000-49,999",
      "monthly_income": 2482.0,
      "is_homeowner": true,
      "state": "NV",
      "in_group": false,
      "credit_score_lower": 611,
      "credit_score_upper": 630,
      "debt_to_income": 0.54,
      "current_credit_lines": 9,
      "revolving_balance": 5818.0,
      "bankcard_utilization": 0.99,
      "delinquencies_7y": 1,
      "amount_delinquent": 3804.0,
      "public_records": 2,
      "loan_amount": 19000.0,
      "term": 60,
      "listing_category": 7,
      "lender_yield": 0.2132,
      "monthly_payment": 411.67,
      "total_inquiries": 11,
      "inquiries_6m": 5,
      "total_trades": 12,
      "trades_never_delinquent": 54.03309101465359,
      "available_credit": 318.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 40,
    "name": "High Risk Profile 15",
    "description": "High DTI 65%, delinquencies",
    "tags": [
      "high-risk",
      "rejected-likely"
    ],
    "loan_status": 2,
    "data": {
      "employment_status": "Full-time",
      "employment_duration": 46,
      "income_range": "$25,000-49,999",
      "monthly_income": 4332.0,
      "is_homeowner": true,
      "state": "NY",
      "in_group": false,
      "credit_score_lower": 581,
      "credit_score_upper": 600,
      "debt_to_income": 0.65,
      "current_credit_lines": 7,
      "revolving_balance": 17609.0,
      "bankcard_utilization": 0.78,
      "delinquencies_7y": 8,
      "amount_delinquent": 4408.0,
      "public_records": 1,
      "loan_amount": 18000.0,
      "term": 60,
      "listing_category": 6,
      "lender_yield": 0.2313,
      "monthly_payment": 390.0,
      "total_inquiries": 10,
      "inquiries_6m": 4,
      "total_trades": 19,
      "trades_never_delinquent": 54.45037929864214,
      "available_credit": 1029.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0
    },
    "prediction": {
      "approved": false,
      "probability": 0.0005555555555555556
    },
    "alternatives": [],
    "category": "bad"
  },
  {
    "id": 100,
    "name": "Borderline Case 1",
    "description": "Found in actual dataset. Initially rejected but easily fixable.",
    "tags": [
      "data-driven",
      "borderline"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 36,
      "lender_yield": 0.1415,
      "listing_category": 1,
      "employment_duration": 7,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 800,
      "credit_score_upper": 819,
      "debt_to_income": 0.21,
      "current_credit_lines": 8,
      "revolving_balance": 14085.0,
      "bankcard_utilization": 0.57,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 5,
      "inquiries_6m": 1,
      "total_trades": 17,
      "trades_never_delinquent": 0.88,
      "available_credit": 9741.0,
      "investors": 337,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5000.0,
      "loan_amount": 15000.0,
      "monthly_payment": 521.08,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.4938888888888889
    },
    "alternatives": [
      {
        "amount": 15000,
        "term": 60,
        "yield": 0.1215,
        "probability": 0.5705555555555555,
        "monthly_payment": 268.45746996466437
      },
      {
        "amount": 15000,
        "term": 60,
        "yield": 0.1315,
        "probability": 0.5605555555555556,
        "monthly_payment": 290.55273498233225
      },
      {
        "amount": 14000,
        "term": 60,
        "yield": 0.1215,
        "probability": 0.5705555555555555,
        "monthly_payment": 250.56030530035338
      }
    ]
  },
  {
    "id": 101,
    "name": "Borderline Case 2",
    "description": "Found in actual dataset. Initially rejected but easily fixable.",
    "tags": [
      "data-driven",
      "borderline"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 36,
      "lender_yield": 0.1459,
      "listing_category": 1,
      "employment_duration": 19,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.25,
      "current_credit_lines": 7,
      "revolving_balance": 3735.0,
      "bankcard_utilization": 0.61,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 4,
      "inquiries_6m": 0,
      "total_trades": 18,
      "trades_never_delinquent": 0.88,
      "available_credit": 2365.0,
      "investors": 65,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2253.333333,
      "loan_amount": 2700.0,
      "monthly_payment": 94.38,
      "employment_status": "Other",
      "state": "PA",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.49722222222222223
    },
    "alternatives": [
      {
        "amount": 2700,
        "term": 60,
        "yield": 0.1259,
        "probability": 0.5672222222222222,
        "monthly_payment": 48.86542289239205
      },
      {
        "amount": 2700,
        "term": 60,
        "yield": 0.1359,
        "probability": 0.5372222222222222,
        "monthly_payment": 52.74671144619602
      },
      {
        "amount": 1700,
        "term": 60,
        "yield": 0.1259,
        "probability": 0.5672222222222222,
        "monthly_payment": 30.76711811743203
      }
    ]
  },
  {
    "id": 102,
    "name": "Borderline Case 3",
    "description": "Found in actual dataset. Initially rejected but easily fixable.",
    "tags": [
      "data-driven",
      "borderline"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 60,
      "lender_yield": 0.173,
      "listing_category": 14,
      "employment_duration": 170,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 700,
      "credit_score_upper": 719,
      "debt_to_income": 0.39,
      "current_credit_lines": 16,
      "revolving_balance": 16804.0,
      "bankcard_utilization": 0.32,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 2,
      "inquiries_6m": 1,
      "total_trades": 43,
      "trades_never_delinquent": 1.0,
      "available_credit": 24577.0,
      "investors": 26,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 11250.0,
      "loan_amount": 11000.0,
      "monthly_payment": 281.13,
      "employment_status": "Other",
      "state": "AZ",
      "income_range": "$100,000+",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.49666666666666665
    },
    "alternatives": [
      {
        "amount": 11000,
        "term": 36,
        "yield": 0.153,
        "probability": 0.5233333333333333,
        "monthly_payment": 414.3823699421966
      },
      {
        "amount": 11000,
        "term": 36,
        "yield": 0.163,
        "probability": 0.5133333333333333,
        "monthly_payment": 441.46618497109836
      },
      {
        "amount": 10000,
        "term": 36,
        "yield": 0.153,
        "probability": 0.5233333333333333,
        "monthly_payment": 376.71124540199685
      }
    ]
  },
  {
    "id": 103,
    "name": "Borderline Case 4",
    "description": "Found in actual dataset. Initially rejected but easily fixable.",
    "tags": [
      "data-driven",
      "borderline"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 36,
      "lender_yield": 0.1399,
      "listing_category": 3,
      "employment_duration": 62,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.25,
      "current_credit_lines": 5,
      "revolving_balance": 29954.0,
      "bankcard_utilization": 0.76,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 14,
      "inquiries_6m": 2,
      "total_trades": 12,
      "trades_never_delinquent": 0.76,
      "available_credit": 9446.0,
      "investors": 406,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 4000.0,
      "loan_amount": 15000.0,
      "monthly_payment": 511.05,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.4305555555555555
    },
    "alternatives": [
      {
        "amount": 14000,
        "term": 60,
        "yield": 0.1199,
        "probability": 0.5072222222222221,
        "monthly_payment": 245.2747762687634
      },
      {
        "amount": 13000,
        "term": 60,
        "yield": 0.1199,
        "probability": 0.5172222222222222,
        "monthly_payment": 227.75514939242316
      },
      {
        "amount": 13000,
        "term": 60,
        "yield": 0.1299,
        "probability": 0.5072222222222221,
        "monthly_payment": 246.75057469621154
      }
    ]
  },
  {
    "id": 104,
    "name": "Borderline Case 5",
    "description": "Found in actual dataset. Initially rejected but easily fixable.",
    "tags": [
      "data-driven",
      "borderline"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 36,
      "lender_yield": 0.14,
      "listing_category": 3,
      "employment_duration": 8,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 680,
      "credit_score_upper": 699,
      "debt_to_income": 0.2258810901466056,
      "current_credit_lines": 11,
      "revolving_balance": 34918.0,
      "bankcard_utilization": 0.66,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 2,
      "inquiries_6m": 2,
      "total_trades": 23,
      "trades_never_delinquent": 0.86,
      "available_credit": 17582.0,
      "investors": 238,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 6250.0,
      "loan_amount": 10000.0,
      "monthly_payment": 346.65,
      "employment_status": "Self-employed",
      "state": "AZ",
      "income_range": "$75,000-99,999",
      "income_verifiable": false
    },
    "prediction": {
      "approved": false,
      "probability": 0.4305555555555556
    },
    "alternatives": [
      {
        "amount": 10000,
        "term": 60,
        "yield": 0.12,
        "probability": 0.5072222222222221,
        "monthly_payment": 178.27714285714282
      },
      {
        "amount": 9000,
        "term": 60,
        "yield": 0.12,
        "probability": 0.5072222222222221,
        "monthly_payment": 160.44942857142854
      },
      {
        "amount": 8000,
        "term": 60,
        "yield": 0.12,
        "probability": 0.5072222222222221,
        "monthly_payment": 142.62171428571426
      }
    ]
  }
];
