const EXAMPLES = [
  {
    "id": 1,
    "name": "Approved Profile 1",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.0929,
      "listing_category": 1,
      "employment_duration": 273,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.18,
      "current_credit_lines": 8,
      "revolving_balance": 3073.0,
      "bankcard_utilization": 0.59,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 2,
      "total_inquiries": 2,
      "inquiries_6m": 0,
      "total_trades": 30,
      "trades_never_delinquent": 83.0,
      "available_credit": 2127.0,
      "investors": 196,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3941.666667,
      "loan_amount": 12000.0,
      "monthly_payment": 343.21,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.6033333333333334
    },
    "alternatives": []
  },
  {
    "id": 2,
    "name": "Approved Profile 2",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.2599,
      "listing_category": 1,
      "employment_duration": 60,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.17,
      "current_credit_lines": 6,
      "revolving_balance": 636.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 31,
      "amount_delinquent": 32110.0,
      "public_records": 2,
      "total_inquiries": 1,
      "inquiries_6m": 1,
      "total_trades": 32,
      "trades_never_delinquent": 66.0,
      "available_credit": 14271.0,
      "investors": 15,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 4750.0,
      "loan_amount": 5000.0,
      "monthly_payment": 204.1,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.5838888888888888
    },
    "alternatives": []
  },
  {
    "id": 3,
    "name": "Approved Profile 3",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.0699,
      "listing_category": 7,
      "employment_duration": 104,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 780,
      "credit_score_upper": 799,
      "debt_to_income": 0.07,
      "current_credit_lines": 4,
      "revolving_balance": 2467.0,
      "bankcard_utilization": 0.25,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 24,
      "trades_never_delinquent": 100.0,
      "available_credit": 7033.0,
      "investors": 133,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 4166.666667,
      "loan_amount": 7000.0,
      "monthly_payment": 219.32,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.7166666666666668
    },
    "alternatives": []
  },
  {
    "id": 4,
    "name": "Approved Profile 4",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.1149,
      "listing_category": 0,
      "employment_duration": 47,
      "is_homeowner": true,
      "in_group": true,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.4,
      "current_credit_lines": 16,
      "revolving_balance": 5074.0,
      "bankcard_utilization": 0.41,
      "delinquencies_7y": 7,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 7,
      "inquiries_6m": 1,
      "total_trades": 47,
      "trades_never_delinquent": 91.0,
      "available_credit": 3638.0,
      "investors": 4,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3833.333333,
      "loan_amount": 3500.0,
      "monthly_payment": 117.91,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.5672222222222222
    },
    "alternatives": []
  },
  {
    "id": 5,
    "name": "Approved Profile 5",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.1199,
      "listing_category": 1,
      "employment_duration": 31,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 800,
      "credit_score_upper": 819,
      "debt_to_income": 0.06,
      "current_credit_lines": 10,
      "revolving_balance": 1754.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 6,
      "inquiries_6m": 1,
      "total_trades": 25,
      "trades_never_delinquent": 88.0,
      "available_credit": 24200.0,
      "investors": 258,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 12500.0,
      "loan_amount": 12000.0,
      "monthly_payment": 404.27,
      "employment_status": "Full-time",
      "state": "NY",
      "income_range": "$100,000+",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.8638888888888889
    },
    "alternatives": []
  },
  {
    "id": 6,
    "name": "Approved Profile 6",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.0794,
      "listing_category": 3,
      "employment_duration": 81,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 800,
      "credit_score_upper": 819,
      "debt_to_income": 0.06,
      "current_credit_lines": 8,
      "revolving_balance": 49080.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 1,
      "total_inquiries": 4,
      "inquiries_6m": 0,
      "total_trades": 15,
      "trades_never_delinquent": 86.0,
      "available_credit": 28641.0,
      "investors": 82,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2243.833333,
      "loan_amount": 2500.0,
      "monthly_payment": 78.27,
      "employment_status": "Retired",
      "state": "NY",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.7972222222222222
    },
    "alternatives": []
  },
  {
    "id": 7,
    "name": "Approved Profile 7",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.3077,
      "listing_category": 2,
      "employment_duration": 46,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 740,
      "credit_score_upper": 759,
      "debt_to_income": 0.1813837046641336,
      "current_credit_lines": 9,
      "revolving_balance": 4806.0,
      "bankcard_utilization": 0.51,
      "delinquencies_7y": 21,
      "amount_delinquent": 0.0,
      "public_records": 2,
      "total_inquiries": 7,
      "inquiries_6m": 0,
      "total_trades": 20,
      "trades_never_delinquent": 86.0,
      "available_credit": 2680.0,
      "investors": 64,
      "investment_friends_amount": 0.0,
      "recommendations": 1,
      "monthly_income": 8333.333333,
      "loan_amount": 4000.0,
      "monthly_payment": 173.71,
      "employment_status": "Self-employed",
      "state": "AZ",
      "income_range": "$100,000+",
      "income_verifiable": false
    },
    "prediction": {
      "approved": true,
      "probability": 0.5466666666666667
    },
    "alternatives": []
  },
  {
    "id": 8,
    "name": "Approved Profile 8",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.061,
      "listing_category": 7,
      "employment_duration": 73,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 800,
      "credit_score_upper": 819,
      "debt_to_income": 0.04,
      "current_credit_lines": 9,
      "revolving_balance": 526.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 2,
      "inquiries_6m": 1,
      "total_trades": 15,
      "trades_never_delinquent": 100.0,
      "available_credit": 52860.0,
      "investors": 282,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 16666.666667,
      "loan_amount": 3000.0,
      "monthly_payment": 92.77,
      "employment_status": "Full-time",
      "state": "NY",
      "income_range": "$100,000+",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.8972222222222223
    },
    "alternatives": []
  },
  {
    "id": 9,
    "name": "Approved Profile 9",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.2195,
      "listing_category": 1,
      "employment_duration": 22,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 780,
      "credit_score_upper": 799,
      "debt_to_income": 0.24,
      "current_credit_lines": 5,
      "revolving_balance": 1697.0,
      "bankcard_utilization": 0.28,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 15,
      "trades_never_delinquent": 100.0,
      "available_credit": 4303.0,
      "investors": 560,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 6666.666667,
      "loan_amount": 15000.0,
      "monthly_payment": 580.25,
      "employment_status": "Full-time",
      "state": "NY",
      "income_range": "$75,000-99,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.6738888888888889
    },
    "alternatives": []
  },
  {
    "id": 10,
    "name": "Approved Profile 10",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.1015,
      "listing_category": 1,
      "employment_duration": 16,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 740,
      "credit_score_upper": 759,
      "debt_to_income": 0.15,
      "current_credit_lines": 9,
      "revolving_balance": 1538.0,
      "bankcard_utilization": 0.15,
      "delinquencies_7y": 8,
      "amount_delinquent": 0.0,
      "public_records": 1,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 32,
      "trades_never_delinquent": 87.0,
      "available_credit": 1695.0,
      "investors": 154,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3250.0,
      "loan_amount": 6000.0,
      "monthly_payment": 191.66666666666663,
      "employment_status": "Other",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.7038888888888889
    },
    "alternatives": []
  },
  {
    "id": 11,
    "name": "Approved Profile 11",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.0725,
      "listing_category": 0,
      "employment_duration": 44,
      "is_homeowner": true,
      "in_group": true,
      "credit_score_lower": 780,
      "credit_score_upper": 799,
      "debt_to_income": 0.29,
      "current_credit_lines": 5,
      "revolving_balance": 0.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 2,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 2,
      "inquiries_6m": 0,
      "total_trades": 12,
      "trades_never_delinquent": 75.0,
      "available_credit": 1200.0,
      "investors": 34,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2666.666667,
      "loan_amount": 8500.0,
      "monthly_payment": 266.36,
      "employment_status": "Self-employed",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.7072222222222222
    },
    "alternatives": []
  },
  {
    "id": 12,
    "name": "Approved Profile 12",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.08,
      "listing_category": 7,
      "employment_duration": 69,
      "is_homeowner": false,
      "in_group": true,
      "credit_score_lower": 780,
      "credit_score_upper": 799,
      "debt_to_income": 0.02,
      "current_credit_lines": 3,
      "revolving_balance": 0.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 2,
      "inquiries_6m": 0,
      "total_trades": 21,
      "trades_never_delinquent": 100.0,
      "available_credit": 50000.0,
      "investors": 282,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 37833.333333,
      "loan_amount": 10000.0,
      "monthly_payment": 313.36,
      "employment_status": "Full-time",
      "state": "NY",
      "income_range": "$100,000+",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.9305555555555557
    },
    "alternatives": []
  },
  {
    "id": 13,
    "name": "Approved Profile 13",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.1634,
      "listing_category": 3,
      "employment_duration": 9,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.3397540941845451,
      "current_credit_lines": 17,
      "revolving_balance": 1967.0,
      "bankcard_utilization": 0.3,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 18,
      "trades_never_delinquent": 88.0,
      "available_credit": 4533.0,
      "investors": 25,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2500.0,
      "loan_amount": 3500.0,
      "monthly_payment": 125.38,
      "employment_status": "Self-employed",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": false
    },
    "prediction": {
      "approved": true,
      "probability": 0.6072222222222222
    },
    "alternatives": []
  },
  {
    "id": 14,
    "name": "Approved Profile 14",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.115,
      "listing_category": 0,
      "employment_duration": 21,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 740,
      "credit_score_upper": 759,
      "debt_to_income": 0.32,
      "current_credit_lines": 14,
      "revolving_balance": 50265.0,
      "bankcard_utilization": 0.84,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 4,
      "inquiries_6m": 0,
      "total_trades": 37,
      "trades_never_delinquent": 100.0,
      "available_credit": 9285.0,
      "investors": 84,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3750.0,
      "loan_amount": 5000.0,
      "monthly_payment": 167.27,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.5505555555555555
    },
    "alternatives": []
  },
  {
    "id": 15,
    "name": "Approved Profile 15",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.074,
      "listing_category": 6,
      "employment_duration": 15,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 780,
      "credit_score_upper": 799,
      "debt_to_income": 0.03,
      "current_credit_lines": 15,
      "revolving_balance": 28963.0,
      "bankcard_utilization": 0.19,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 9,
      "inquiries_6m": 5,
      "total_trades": 32,
      "trades_never_delinquent": 93.0,
      "available_credit": 122438.0,
      "investors": 274,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 10416.666667,
      "loan_amount": 6300.0,
      "monthly_payment": 198.58,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$100,000+",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.8438888888888889
    },
    "alternatives": []
  },
  {
    "id": 16,
    "name": "Approved Profile 16",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.079,
      "listing_category": 1,
      "employment_duration": 91,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.08,
      "current_credit_lines": 1,
      "revolving_balance": 1513.0,
      "bankcard_utilization": 0.5,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 1,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 6,
      "trades_never_delinquent": 100.0,
      "available_credit": 1487.0,
      "investors": 76,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2803.5,
      "loan_amount": 5000.0,
      "monthly_payment": 158.77,
      "employment_status": "Other",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.6033333333333334
    },
    "alternatives": []
  },
  {
    "id": 17,
    "name": "Approved Profile 17",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.08,
      "listing_category": 4,
      "employment_duration": 53,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.01,
      "current_credit_lines": 12,
      "revolving_balance": 1544.0,
      "bankcard_utilization": 0.05,
      "delinquencies_7y": 5,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 7,
      "inquiries_6m": 0,
      "total_trades": 14,
      "trades_never_delinquent": 92.0,
      "available_credit": 28756.0,
      "investors": 30,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 7953.666667,
      "loan_amount": 1000.0,
      "monthly_payment": 31.8,
      "employment_status": "Full-time",
      "state": "NY",
      "income_range": "$75,000-99,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.8905555555555557
    },
    "alternatives": []
  },
  {
    "id": 18,
    "name": "Approved Profile 18",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.07,
      "listing_category": 0,
      "employment_duration": 24,
      "is_homeowner": false,
      "in_group": true,
      "credit_score_lower": 760,
      "credit_score_upper": 779,
      "debt_to_income": 0.19,
      "current_credit_lines": 16,
      "revolving_balance": 7641.0,
      "bankcard_utilization": 0.06,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 19,
      "trades_never_delinquent": 100.0,
      "available_credit": 46205.0,
      "investors": 97,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 7083.333333,
      "loan_amount": 2000.0,
      "monthly_payment": 62.21,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$75,000-99,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.9205555555555556
    },
    "alternatives": []
  },
  {
    "id": 19,
    "name": "Approved Profile 19",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.0538,
      "listing_category": 1,
      "employment_duration": 28,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 780,
      "credit_score_upper": 799,
      "debt_to_income": 0.09,
      "current_credit_lines": 10,
      "revolving_balance": 57.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 1,
      "amount_delinquent": 19.0,
      "public_records": 0,
      "total_inquiries": 5,
      "inquiries_6m": 1,
      "total_trades": 27,
      "trades_never_delinquent": 96.0,
      "available_credit": 31543.0,
      "investors": 96,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 4333.333333,
      "loan_amount": 2500.0,
      "monthly_payment": 76.49,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.7838888888888889
    },
    "alternatives": []
  },
  {
    "id": 20,
    "name": "Approved Profile 20",
    "description": "High-quality application meeting all lending criteria.",
    "tags": [
      "low-risk",
      "stable"
    ],
    "loan_status": 0,
    "category": "good",
    "data": {
      "term": 36,
      "lender_yield": 0.07,
      "listing_category": 2,
      "employment_duration": 75,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 780,
      "credit_score_upper": 799,
      "debt_to_income": 0.14,
      "current_credit_lines": 3,
      "revolving_balance": 9700.0,
      "bankcard_utilization": 0.26,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 13,
      "trades_never_delinquent": 100.0,
      "available_credit": 26800.0,
      "investors": 226,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 4333.333333,
      "loan_amount": 8000.0,
      "monthly_payment": 250.69,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": true,
      "probability": 0.8405555555555556
    },
    "alternatives": []
  },
  {
    "id": 101,
    "name": "Near-Approval Profile 1",
    "description": "Rejected initially but has clear paths to approval.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 36,
      "lender_yield": 0.1521,
      "listing_category": 7,
      "employment_duration": 52,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 700,
      "credit_score_upper": 719,
      "debt_to_income": 0.48,
      "current_credit_lines": 13,
      "revolving_balance": 11839.0,
      "bankcard_utilization": 0.3,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 24,
      "trades_never_delinquent": 79.0,
      "available_credit": 22691.0,
      "investors": 43,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2086.0,
      "loan_amount": 2000.0,
      "monthly_payment": 70.52,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.4372222222222222
    },
    "alternatives": [
      {
        "amount": 2000,
        "term": 60,
        "yield": 0.1321,
        "probability": 0.5138888888888888,
        "monthly_payment": 36.748291913214985
      },
      {
        "amount": 1000,
        "term": 60,
        "yield": 0.1321,
        "probability": 0.5138888888888888,
        "monthly_payment": 18.374145956607492
      },
      {
        "amount": 2000,
        "term": 36,
        "yield": 0.1321,
        "probability": 0.5272222222222221,
        "monthly_payment": 61.24715318869164
      }
    ]
  },
  {
    "id": 102,
    "name": "Near-Approval Profile 2",
    "description": "Rejected initially but has clear paths to approval.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 36,
      "lender_yield": 0.1526,
      "listing_category": 7,
      "employment_duration": 22,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 700,
      "credit_score_upper": 719,
      "debt_to_income": 0.14,
      "current_credit_lines": 11,
      "revolving_balance": 110.0,
      "bankcard_utilization": 0.02,
      "delinquencies_7y": 41,
      "amount_delinquent": 6796.0,
      "public_records": 2,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 19,
      "trades_never_delinquent": 73.0,
      "available_credit": 3990.0,
      "investors": 182,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3750.0,
      "loan_amount": 9500.0,
      "monthly_payment": 335.21,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.4372222222222222
    },
    "alternatives": [
      {
        "amount": 9500,
        "term": 60,
        "yield": 0.1326,
        "probability": 0.5172222222222222,
        "monthly_payment": 174.76610484927912
      },
      {
        "amount": 8500,
        "term": 60,
        "yield": 0.1326,
        "probability": 0.5172222222222222,
        "monthly_payment": 156.36967275988133
      },
      {
        "amount": 7500,
        "term": 60,
        "yield": 0.1326,
        "probability": 0.5172222222222222,
        "monthly_payment": 137.9732406704835
      }
    ]
  },
  {
    "id": 103,
    "name": "Near-Approval Profile 3",
    "description": "Rejected initially but has clear paths to approval.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 60,
      "lender_yield": 0.1479,
      "listing_category": 1,
      "employment_duration": 311,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.11,
      "current_credit_lines": 7,
      "revolving_balance": 17079.0,
      "bankcard_utilization": 0.9,
      "delinquencies_7y": 10,
      "amount_delinquent": 316.0,
      "public_records": 0,
      "total_inquiries": 3,
      "inquiries_6m": 0,
      "total_trades": 27,
      "trades_never_delinquent": 85.0,
      "available_credit": 1821.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5666.666667,
      "loan_amount": 11500.0,
      "monthly_payment": 278.38,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.47
    },
    "alternatives": [
      {
        "amount": 11500,
        "term": 36,
        "yield": 0.1279,
        "probability": 0.5733333333333334,
        "monthly_payment": 401.2260761775976
      },
      {
        "amount": 11500,
        "term": 36,
        "yield": 0.1379,
        "probability": 0.5033333333333333,
        "monthly_payment": 432.59637142213205
      },
      {
        "amount": 10500,
        "term": 36,
        "yield": 0.1279,
        "probability": 0.5733333333333334,
        "monthly_payment": 366.33685216215423
      }
    ]
  },
  {
    "id": 104,
    "name": "Near-Approval Profile 4",
    "description": "Rejected initially but has clear paths to approval.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 60,
      "lender_yield": 0.2109,
      "listing_category": 7,
      "employment_duration": 151,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 720,
      "credit_score_upper": 739,
      "debt_to_income": 0.46,
      "current_credit_lines": 14,
      "revolving_balance": 20126.0,
      "bankcard_utilization": 0.29,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 11,
      "inquiries_6m": 2,
      "total_trades": 30,
      "trades_never_delinquent": 83.0,
      "available_credit": 35934.0,
      "investors": 1,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2833.333333,
      "loan_amount": 8600.0,
      "monthly_payment": 237.96,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.5
    },
    "alternatives": [
      {
        "amount": 8600,
        "term": 36,
        "yield": 0.1909,
        "probability": 0.5133333333333333,
        "monthly_payment": 358.98975817923184
      },
      {
        "amount": 8600,
        "term": 36,
        "yield": 0.2009,
        "probability": 0.5133333333333333,
        "monthly_payment": 377.79487908961596
      },
      {
        "amount": 7600,
        "term": 36,
        "yield": 0.1909,
        "probability": 0.5133333333333333,
        "monthly_payment": 317.2467630421118
      }
    ]
  },
  {
    "id": 105,
    "name": "Near-Approval Profile 5",
    "description": "Rejected initially but has clear paths to approval.",
    "tags": [
      "borderline",
      "recoverable"
    ],
    "loan_status": 2,
    "category": "near-approval",
    "data": {
      "term": 36,
      "lender_yield": 0.13,
      "listing_category": 1,
      "employment_duration": 11,
      "is_homeowner": true,
      "in_group": true,
      "credit_score_lower": 700,
      "credit_score_upper": 719,
      "debt_to_income": 0.4,
      "current_credit_lines": 17,
      "revolving_balance": 11844.0,
      "bankcard_utilization": 0.31,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 9,
      "inquiries_6m": 1,
      "total_trades": 17,
      "trades_never_delinquent": 100.0,
      "available_credit": 20296.0,
      "investors": 248,
      "investment_friends_amount": 0.0,
      "recommendations": 1,
      "monthly_income": 2535.166667,
      "loan_amount": 10000.0,
      "monthly_payment": 341.78,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.49333333333333335
    },
    "alternatives": [
      {
        "amount": 8000,
        "term": 60,
        "yield": 0.11,
        "probability": 0.5166666666666666,
        "monthly_payment": 138.81526153846153
      },
      {
        "amount": 8000,
        "term": 60,
        "yield": 0.12,
        "probability": 0.5133333333333333,
        "monthly_payment": 151.43483076923076
      },
      {
        "amount": 7000,
        "term": 60,
        "yield": 0.11,
        "probability": 0.5166666666666666,
        "monthly_payment": 121.46335384615381
      }
    ]
  },
  {
    "id": 201,
    "name": "High-Risk Profile 1",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.17,
      "listing_category": 0,
      "employment_duration": 57,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 640,
      "credit_score_upper": 659,
      "debt_to_income": 0.1,
      "current_credit_lines": 1,
      "revolving_balance": 0.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 12,
      "amount_delinquent": 178.0,
      "public_records": 0,
      "total_inquiries": 1,
      "inquiries_6m": 1,
      "total_trades": 9,
      "trades_never_delinquent": 60.0,
      "available_credit": 0.0,
      "investors": 129,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2083.333333,
      "loan_amount": 6001.0,
      "monthly_payment": 216.95,
      "employment_status": "Full-time",
      "state": "NY",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.3605555555555555
    },
    "alternatives": []
  },
  {
    "id": 202,
    "name": "High-Risk Profile 2",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.14,
      "listing_category": 0,
      "employment_duration": 31,
      "is_homeowner": true,
      "in_group": true,
      "credit_score_lower": 640,
      "credit_score_upper": 659,
      "debt_to_income": 0.18,
      "current_credit_lines": 5,
      "revolving_balance": 0.0,
      "bankcard_utilization": 0.0,
      "delinquencies_7y": 32,
      "amount_delinquent": 3926.0,
      "public_records": 1,
      "total_inquiries": 4,
      "inquiries_6m": 1,
      "total_trades": 14,
      "trades_never_delinquent": 52.0,
      "available_credit": 0.0,
      "investors": 200,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3900.0,
      "loan_amount": 4800.0,
      "monthly_payment": 167.67,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.38055555555555554
    },
    "alternatives": []
  },
  {
    "id": 203,
    "name": "High-Risk Profile 3",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 60,
      "lender_yield": 0.1745,
      "listing_category": 1,
      "employment_duration": 47,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 700,
      "credit_score_upper": 719,
      "debt_to_income": 0.17,
      "current_credit_lines": 6,
      "revolving_balance": 5682.0,
      "bankcard_utilization": 0.48,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 1,
      "inquiries_6m": 1,
      "total_trades": 10,
      "trades_never_delinquent": 80.0,
      "available_credit": 6018.0,
      "investors": 74,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2500.0,
      "loan_amount": 8000.0,
      "monthly_payment": 205.11,
      "employment_status": "Other",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.2538888888888889
    },
    "alternatives": []
  },
  {
    "id": 204,
    "name": "High-Risk Profile 4",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.3077,
      "listing_category": 3,
      "employment_duration": 72,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 660,
      "credit_score_upper": 679,
      "debt_to_income": 0.21,
      "current_credit_lines": 10,
      "revolving_balance": 5264.0,
      "bankcard_utilization": 0.75,
      "delinquencies_7y": 8,
      "amount_delinquent": 0.0,
      "public_records": 2,
      "total_inquiries": 2,
      "inquiries_6m": 1,
      "total_trades": 27,
      "trades_never_delinquent": 66.0,
      "available_credit": 1368.0,
      "investors": 16,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5416.666667,
      "loan_amount": 4000.0,
      "monthly_payment": 173.71,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.2705555555555556
    },
    "alternatives": []
  },
  {
    "id": 205,
    "name": "High-Risk Profile 5",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.2599,
      "listing_category": 1,
      "employment_duration": 80,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 660,
      "credit_score_upper": 679,
      "debt_to_income": 0.18,
      "current_credit_lines": 4,
      "revolving_balance": 3133.0,
      "bankcard_utilization": 0.52,
      "delinquencies_7y": 3,
      "amount_delinquent": 0.0,
      "public_records": 1,
      "total_inquiries": 8,
      "inquiries_6m": 1,
      "total_trades": 22,
      "trades_never_delinquent": 81.0,
      "available_credit": 2867.0,
      "investors": 98,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5416.666667,
      "loan_amount": 4500.0,
      "monthly_payment": 183.69,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.29388888888888887
    },
    "alternatives": []
  },
  {
    "id": 206,
    "name": "High-Risk Profile 6",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.185,
      "listing_category": 0,
      "employment_duration": 76,
      "is_homeowner": false,
      "in_group": true,
      "credit_score_lower": 600,
      "credit_score_upper": 619,
      "debt_to_income": 0.4,
      "current_credit_lines": 7,
      "revolving_balance": 8304.0,
      "bankcard_utilization": 0.94,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 8,
      "inquiries_6m": 3,
      "total_trades": 17,
      "trades_never_delinquent": 76.0,
      "available_credit": 460.0,
      "investors": 43,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 2916.666667,
      "loan_amount": 4000.0,
      "monthly_payment": 127.77777777777777,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.13055555555555556
    },
    "alternatives": []
  },
  {
    "id": 207,
    "name": "High-Risk Profile 7",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.3335,
      "listing_category": 1,
      "employment_duration": 96,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 640,
      "credit_score_upper": 659,
      "debt_to_income": 0.43,
      "current_credit_lines": 6,
      "revolving_balance": 9334.0,
      "bankcard_utilization": 0.22,
      "delinquencies_7y": 2,
      "amount_delinquent": 2114.0,
      "public_records": 0,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 16,
      "trades_never_delinquent": 61.0,
      "available_credit": 19498.0,
      "investors": 204,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 4266.333333,
      "loan_amount": 7500.0,
      "monthly_payment": 336.52,
      "employment_status": "Other",
      "state": "PA",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.3933333333333333
    },
    "alternatives": []
  },
  {
    "id": 208,
    "name": "High-Risk Profile 8",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.2499,
      "listing_category": 6,
      "employment_duration": 52,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 640,
      "credit_score_upper": 659,
      "debt_to_income": 0.1,
      "current_credit_lines": 3,
      "revolving_balance": 2219.0,
      "bankcard_utilization": 0.98,
      "delinquencies_7y": 39,
      "amount_delinquent": 0.0,
      "public_records": 1,
      "total_inquiries": 5,
      "inquiries_6m": 0,
      "total_trades": 48,
      "trades_never_delinquent": 69.0,
      "available_credit": 31.0,
      "investors": 22,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3333.333333,
      "loan_amount": 5500.0,
      "monthly_payment": 221.57,
      "employment_status": "Other",
      "state": "NY",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.2672222222222222
    },
    "alternatives": []
  },
  {
    "id": 209,
    "name": "High-Risk Profile 9",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.2437,
      "listing_category": 1,
      "employment_duration": 74,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 660,
      "credit_score_upper": 679,
      "debt_to_income": 0.66,
      "current_credit_lines": 8,
      "revolving_balance": 12371.0,
      "bankcard_utilization": 0.98,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 1,
      "inquiries_6m": 0,
      "total_trades": 25,
      "trades_never_delinquent": 100.0,
      "available_credit": 129.0,
      "investors": 72,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3750.0,
      "loan_amount": 7000.0,
      "monthly_payment": 279.69,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.13055555555555556
    },
    "alternatives": []
  },
  {
    "id": 210,
    "name": "High-Risk Profile 10",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.159,
      "listing_category": 1,
      "employment_duration": 45,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 660,
      "credit_score_upper": 679,
      "debt_to_income": 0.15,
      "current_credit_lines": 17,
      "revolving_balance": 13267.0,
      "bankcard_utilization": 0.8,
      "delinquencies_7y": 1,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 11,
      "inquiries_6m": 8,
      "total_trades": 49,
      "trades_never_delinquent": 85.0,
      "available_credit": 3310.0,
      "investors": 112,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 7416.666667,
      "loan_amount": 3900.0,
      "monthly_payment": 138.85,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$75,000-99,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.2838888888888889
    },
    "alternatives": []
  },
  {
    "id": 211,
    "name": "High-Risk Profile 11",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 12,
      "lender_yield": 0.0601,
      "listing_category": 2,
      "employment_duration": 119,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 660,
      "credit_score_upper": 679,
      "debt_to_income": 0.11,
      "current_credit_lines": 7,
      "revolving_balance": 2561.0,
      "bankcard_utilization": 0.94,
      "delinquencies_7y": 20,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 4,
      "inquiries_6m": 0,
      "total_trades": 22,
      "trades_never_delinquent": 65.0,
      "available_credit": 149.0,
      "investors": 8,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5583.333333,
      "loan_amount": 2000.0,
      "monthly_payment": 173.06,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.43333333333333335
    },
    "alternatives": []
  },
  {
    "id": 212,
    "name": "High-Risk Profile 12",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.33,
      "listing_category": 1,
      "employment_duration": 320,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 680,
      "credit_score_upper": 699,
      "debt_to_income": 0.41,
      "current_credit_lines": 13,
      "revolving_balance": 4579.0,
      "bankcard_utilization": 0.22,
      "delinquencies_7y": 1,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 5,
      "inquiries_6m": 2,
      "total_trades": 27,
      "trades_never_delinquent": 48.0,
      "available_credit": 2781.0,
      "investors": 6,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3583.333333,
      "loan_amount": 4350.0,
      "monthly_payment": 138.95833333333331,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.27666666666666667
    },
    "alternatives": []
  },
  {
    "id": 213,
    "name": "High-Risk Profile 13",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.2187,
      "listing_category": 7,
      "employment_duration": 27,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 620,
      "credit_score_upper": 639,
      "debt_to_income": 0.11,
      "current_credit_lines": 15,
      "revolving_balance": 3912.0,
      "bankcard_utilization": 0.09,
      "delinquencies_7y": 0,
      "amount_delinquent": 6.0,
      "public_records": 1,
      "total_inquiries": 9,
      "inquiries_6m": 2,
      "total_trades": 21,
      "trades_never_delinquent": 91.0,
      "available_credit": 2535.0,
      "investors": 21,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5000.0,
      "loan_amount": 2000.0,
      "monthly_payment": 77.28,
      "employment_status": "Other",
      "state": "AZ",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.38055555555555554
    },
    "alternatives": []
  },
  {
    "id": 214,
    "name": "High-Risk Profile 14",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.1021,
      "listing_category": 1,
      "employment_duration": 153,
      "is_homeowner": true,
      "in_group": false,
      "credit_score_lower": 640,
      "credit_score_upper": 659,
      "debt_to_income": 0.31,
      "current_credit_lines": 11,
      "revolving_balance": 8789.0,
      "bankcard_utilization": 0.91,
      "delinquencies_7y": 9,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 9,
      "inquiries_6m": 1,
      "total_trades": 23,
      "trades_never_delinquent": 73.0,
      "available_credit": 2000.0,
      "investors": 21,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5000.0,
      "loan_amount": 1500.0,
      "monthly_payment": 49.26,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.3566666666666667
    },
    "alternatives": []
  },
  {
    "id": 215,
    "name": "High-Risk Profile 15",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.2099,
      "listing_category": 6,
      "employment_duration": 70,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 620,
      "credit_score_upper": 639,
      "debt_to_income": 0.13,
      "current_credit_lines": 7,
      "revolving_balance": 6143.0,
      "bankcard_utilization": 0.99,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 0,
      "inquiries_6m": 0,
      "total_trades": 22,
      "trades_never_delinquent": 77.0,
      "available_credit": 19.0,
      "investors": 33,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5333.333333,
      "loan_amount": 2000.0,
      "monthly_payment": 76.37,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.3038888888888889
    },
    "alternatives": []
  },
  {
    "id": 216,
    "name": "High-Risk Profile 16",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.29,
      "listing_category": 4,
      "employment_duration": 85,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 620,
      "credit_score_upper": 639,
      "debt_to_income": 0.16,
      "current_credit_lines": 13,
      "revolving_balance": 4269.0,
      "bankcard_utilization": 0.59,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 4,
      "inquiries_6m": 3,
      "total_trades": 17,
      "trades_never_delinquent": 57.99999999999999,
      "available_credit": 1531.0,
      "investors": 125,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 6833.333333,
      "loan_amount": 7500.0,
      "monthly_payment": 318.39,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$75,000-99,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.3005555555555555
    },
    "alternatives": []
  },
  {
    "id": 217,
    "name": "High-Risk Profile 17",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.2048,
      "listing_category": 3,
      "employment_duration": 131,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 700,
      "credit_score_upper": 719,
      "debt_to_income": 0.19,
      "current_credit_lines": 11,
      "revolving_balance": 14887.0,
      "bankcard_utilization": 0.58,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 7,
      "inquiries_6m": 1,
      "total_trades": 22,
      "trades_never_delinquent": 100.0,
      "available_credit": 8466.0,
      "investors": 75,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 10000.0,
      "loan_amount": 5000.0,
      "monthly_payment": 189.61,
      "employment_status": "Other",
      "state": "PA",
      "income_range": "$100,000+",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.32
    },
    "alternatives": []
  },
  {
    "id": 218,
    "name": "High-Risk Profile 18",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.1349,
      "listing_category": 7,
      "employment_duration": 373,
      "is_homeowner": false,
      "in_group": false,
      "credit_score_lower": 680,
      "credit_score_upper": 699,
      "debt_to_income": 0.1,
      "current_credit_lines": 4,
      "revolving_balance": 6676.0,
      "bankcard_utilization": 0.8,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 4,
      "inquiries_6m": 1,
      "total_trades": 10,
      "trades_never_delinquent": 100.0,
      "available_credit": 1637.0,
      "investors": 26,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 3333.333333,
      "loan_amount": 3200.0,
      "monthly_payment": 110.13,
      "employment_status": "Other",
      "state": "AZ",
      "income_range": "$25,000-49,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.30333333333333334
    },
    "alternatives": []
  },
  {
    "id": 219,
    "name": "High-Risk Profile 19",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.23,
      "listing_category": 0,
      "employment_duration": 66,
      "is_homeowner": false,
      "in_group": true,
      "credit_score_lower": 640,
      "credit_score_upper": 659,
      "debt_to_income": 0.3,
      "current_credit_lines": 12,
      "revolving_balance": 1445.0,
      "bankcard_utilization": 0.84,
      "delinquencies_7y": 12,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 7,
      "inquiries_6m": 2,
      "total_trades": 38,
      "trades_never_delinquent": 71.0,
      "available_credit": 261.0,
      "investors": 175,
      "investment_friends_amount": 0.0,
      "recommendations": 1,
      "monthly_income": 4583.333333,
      "loan_amount": 10000.0,
      "monthly_payment": 392.33,
      "employment_status": "Full-time",
      "state": "AZ",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.26
    },
    "alternatives": []
  },
  {
    "id": 220,
    "name": "High-Risk Profile 20",
    "description": "High-risk application with significant credit barriers.",
    "tags": [
      "high-risk",
      "rejected"
    ],
    "loan_status": 3,
    "category": "bad",
    "data": {
      "term": 36,
      "lender_yield": 0.225,
      "listing_category": 0,
      "employment_duration": 176,
      "is_homeowner": true,
      "in_group": true,
      "credit_score_lower": 600,
      "credit_score_upper": 619,
      "debt_to_income": 0.48,
      "current_credit_lines": 25,
      "revolving_balance": 39342.0,
      "bankcard_utilization": 0.96,
      "delinquencies_7y": 0,
      "amount_delinquent": 0.0,
      "public_records": 0,
      "total_inquiries": 56,
      "inquiries_6m": 15,
      "total_trades": 38,
      "trades_never_delinquent": 100.0,
      "available_credit": 1359.0,
      "investors": 185,
      "investment_friends_amount": 0.0,
      "recommendations": 0,
      "monthly_income": 5281.25,
      "loan_amount": 12500.0,
      "monthly_payment": 490.41,
      "employment_status": "Full-time",
      "state": "NY",
      "income_range": "$50,000-74,999",
      "income_verifiable": true
    },
    "prediction": {
      "approved": false,
      "probability": 0.18000000000000002
    },
    "alternatives": []
  }
];
