// Auto-generated by m2cgen
// Feature columns expected:
// ['term', 'lender_yield', 'listing_category', 'employment_duration', 'is_homeowner', 'in_group', 'CreditScoreMean', 'credit_score_lower', 'credit_score_upper', 'debt_to_income', 'current_credit_lines', 'revolving_balance', 'bankcard_utilization', 'delinquencies_7y', 'amount_delinquent', 'public_records', 'total_inquiries', 'inquiries_6m', 'total_trades', 'trades_never_delinquent', 'available_credit', 'investors', 'investment_friends_amount', 'recommendations', 'monthly_income', 'loan_amount', 'monthly_payment', 'LoanToIncome', 'PaymentToIncome', 'LenderYield_mean_by_ListingCategory', 'LenderYield_mean_by_Term', 'EmploymentStatus_Full-time', 'EmploymentStatus_Not employed', 'EmploymentStatus_Part-time', 'EmploymentStatus_Self-employed', 'StateCluster_1', 'StateCluster_2', 'StateCluster_3', 'StateCluster_4', 'StateCluster_5', 'StateCluster_6']

function scoreModel1(input) {
    var var0;
    if (input[6] <= 711.0) {
        var0 = [1.0, 0.0];
    } else {
        var0 = [0.0, 1.0];
    }
    var var1;
    if (input[7] <= 708.0) {
        if (input[10] <= 14.0) {
            var1 = [1.0, 0.0];
        } else {
            var1 = [0.0, 1.0];
        }
    } else {
        var1 = [0.0, 1.0];
    }
    var var2;
    if (input[12] <= 0.4650000184774399) {
        var2 = [0.0, 1.0];
    } else {
        var2 = [1.0, 0.0];
    }
    var var3;
    if (input[12] <= 0.41499999165534973) {
        var3 = [0.0, 1.0];
    } else {
        var3 = [1.0, 0.0];
    }
    var var4;
    if (input[24] <= 4997.5) {
        var4 = [1.0, 0.0];
    } else {
        var4 = [0.0, 1.0];
    }
    var var5;
    if (input[24] <= 4997.5) {
        var5 = [1.0, 0.0];
    } else {
        var5 = [0.0, 1.0];
    }
    var var6;
    if (input[19] <= 96.5) {
        var6 = [1.0, 0.0];
    } else {
        var6 = [0.0, 1.0];
    }
    var var7;
    if (input[8] <= 728.5) {
        var7 = [1.0, 0.0];
    } else {
        var7 = [0.0, 1.0];
    }
    var var8;
    if (input[6] <= 717.0) {
        if (input[20] <= 34720.5) {
            var8 = [1.0, 0.0];
        } else {
            var8 = [0.0, 1.0];
        }
    } else {
        var8 = [0.0, 1.0];
    }
    var var9;
    if (input[24] <= 5157.0) {
        var9 = [1.0, 0.0];
    } else {
        var9 = [0.0, 1.0];
    }
    var var10;
    if (input[20] <= 15071.0) {
        var10 = [1.0, 0.0];
    } else {
        var10 = [0.0, 1.0];
    }
    var var11;
    if (input[12] <= 0.42499999701976776) {
        var11 = [0.0, 1.0];
    } else {
        var11 = [1.0, 0.0];
    }
    var var12;
    if (input[9] <= 0.375) {
        var12 = [0.0, 1.0];
    } else {
        var12 = [1.0, 0.0];
    }
    var var13;
    if (input[7] <= 701.5) {
        var13 = [1.0, 0.0];
    } else {
        var13 = [0.0, 1.0];
    }
    var var14;
    if (input[1] <= 0.13625000044703484) {
        var14 = [0.0, 1.0];
    } else {
        var14 = [1.0, 0.0];
    }
    var var15;
    if (input[30] <= 0.13729749619960785) {
        var15 = [0.0, 1.0];
    } else {
        if (input[27] <= 3.43271803855896) {
            var15 = [0.0, 1.0];
        } else {
            var15 = [1.0, 0.0];
        }
    }
    var var16;
    if (input[20] <= 15426.5) {
        var16 = [1.0, 0.0];
    } else {
        var16 = [0.0, 1.0];
    }
    var var17;
    if (input[20] <= 15426.5) {
        var17 = [1.0, 0.0];
    } else {
        var17 = [0.0, 1.0];
    }
    var var18;
    if (input[1] <= 0.13625000044703484) {
        var18 = [0.0, 1.0];
    } else {
        var18 = [1.0, 0.0];
    }
    var var19;
    if (input[7] <= 714.5) {
        var19 = [1.0, 0.0];
    } else {
        var19 = [0.0, 1.0];
    }
    var var20;
    if (input[6] <= 711.0) {
        var20 = [1.0, 0.0];
    } else {
        var20 = [0.0, 1.0];
    }
    var var21;
    if (input[8] <= 727.0) {
        var21 = [1.0, 0.0];
    } else {
        var21 = [0.0, 1.0];
    }
    var var22;
    if (input[17] <= 0.5) {
        var22 = [0.0, 1.0];
    } else {
        var22 = [1.0, 0.0];
    }
    var var23;
    if (input[12] <= 0.48499999940395355) {
        var23 = [0.0, 1.0];
    } else {
        var23 = [1.0, 0.0];
    }
    var var24;
    if (input[9] <= 0.3799999952316284) {
        var24 = [0.0, 1.0];
    } else {
        var24 = [1.0, 0.0];
    }
    var var25;
    if (input[6] <= 717.0) {
        var25 = [1.0, 0.0];
    } else {
        var25 = [0.0, 1.0];
    }
    var var26;
    if (input[12] <= 0.42499999701976776) {
        var26 = [0.0, 1.0];
    } else {
        var26 = [1.0, 0.0];
    }
    var var27;
    if (input[12] <= 0.42499999701976776) {
        var27 = [0.0, 1.0];
    } else {
        var27 = [1.0, 0.0];
    }
    var var28;
    if (input[7] <= 707.5) {
        var28 = [1.0, 0.0];
    } else {
        var28 = [0.0, 1.0];
    }
    var var29;
    if (input[9] <= 0.375) {
        var29 = [0.0, 1.0];
    } else {
        var29 = [1.0, 0.0];
    }
    var var30;
    if (input[17] <= 0.5) {
        if (input[20] <= 11483.5) {
            var30 = [1.0, 0.0];
        } else {
            var30 = [0.0, 1.0];
        }
    } else {
        var30 = [1.0, 0.0];
    }
    var var31;
    if (input[20] <= 15426.5) {
        var31 = [1.0, 0.0];
    } else {
        var31 = [0.0, 1.0];
    }
    var var32;
    if (input[8] <= 726.5) {
        if (input[11] <= 3516.0) {
            var32 = [0.0, 1.0];
        } else {
            var32 = [1.0, 0.0];
        }
    } else {
        var32 = [0.0, 1.0];
    }
    var var33;
    if (input[8] <= 721.5) {
        var33 = [1.0, 0.0];
    } else {
        var33 = [0.0, 1.0];
    }
    var var34;
    if (input[21] <= 2.0) {
        var34 = [1.0, 0.0];
    } else {
        var34 = [0.0, 1.0];
    }
    var var35;
    if (input[21] <= 1.5) {
        if (input[12] <= 0.3499999903142452) {
            var35 = [0.0, 1.0];
        } else {
            var35 = [1.0, 0.0];
        }
    } else {
        var35 = [0.0, 1.0];
    }
    var var36;
    if (input[12] <= 0.41499999165534973) {
        var36 = [0.0, 1.0];
    } else {
        var36 = [1.0, 0.0];
    }
    var var37;
    if (input[19] <= 92.21287536621094) {
        var37 = [1.0, 0.0];
    } else {
        var37 = [0.0, 1.0];
    }
    var var38;
    if (input[17] <= 1.0) {
        var38 = [0.0, 1.0];
    } else {
        var38 = [1.0, 0.0];
    }
    var var39;
    if (input[0] <= 48.0) {
        var39 = [0.0, 1.0];
    } else {
        if (input[8] <= 720.5) {
            var39 = [1.0, 0.0];
        } else {
            if (input[4] <= 0.5) {
                var39 = [1.0, 0.0];
            } else {
                var39 = [0.0, 1.0];
            }
        }
    }
    var var40;
    if (input[6] <= 717.0) {
        var40 = [1.0, 0.0];
    } else {
        var40 = [0.0, 1.0];
    }
    var var41;
    if (input[19] <= 92.21287536621094) {
        var41 = [1.0, 0.0];
    } else {
        if (input[8] <= 695.5) {
            var41 = [1.0, 0.0];
        } else {
            var41 = [0.0, 1.0];
        }
    }
    var var42;
    if (input[16] <= 3.5) {
        if (input[9] <= 0.42000000178813934) {
            var42 = [0.0, 1.0];
        } else {
            var42 = [1.0, 0.0];
        }
    } else {
        var42 = [1.0, 0.0];
    }
    var var43;
    if (input[11] <= 5054.0) {
        var43 = [0.0, 1.0];
    } else {
        if (input[26] <= 765.5549926757812) {
            var43 = [1.0, 0.0];
        } else {
            var43 = [0.0, 1.0];
        }
    }
    var var44;
    if (input[24] <= 4997.5) {
        var44 = [1.0, 0.0];
    } else {
        if (input[7] <= 681.5) {
            var44 = [1.0, 0.0];
        } else {
            var44 = [0.0, 1.0];
        }
    }
    var var45;
    if (input[8] <= 720.5) {
        var45 = [1.0, 0.0];
    } else {
        var45 = [0.0, 1.0];
    }
    var var46;
    if (input[20] <= 15426.5) {
        var46 = [1.0, 0.0];
    } else {
        var46 = [0.0, 1.0];
    }
    var var47;
    if (input[1] <= 0.16090000048279762) {
        var47 = [0.0, 1.0];
    } else {
        var47 = [1.0, 0.0];
    }
    var var48;
    if (input[24] <= 4997.5) {
        var48 = [1.0, 0.0];
    } else {
        if (input[6] <= 691.5) {
            var48 = [1.0, 0.0];
        } else {
            var48 = [0.0, 1.0];
        }
    }
    var var49;
    if (input[20] <= 15426.5) {
        var49 = [1.0, 0.0];
    } else {
        var49 = [0.0, 1.0];
    }
    var var50;
    if (input[6] <= 711.0) {
        var50 = [1.0, 0.0];
    } else {
        var50 = [0.0, 1.0];
    }
    var var51;
    if (input[8] <= 702.5) {
        var51 = [1.0, 0.0];
    } else {
        var51 = [0.0, 1.0];
    }
    var var52;
    if (input[9] <= 0.3799999952316284) {
        var52 = [0.0, 1.0];
    } else {
        var52 = [1.0, 0.0];
    }
    var var53;
    if (input[20] <= 17884.0) {
        var53 = [1.0, 0.0];
    } else {
        var53 = [0.0, 1.0];
    }
    var var54;
    if (input[8] <= 720.5) {
        var54 = [1.0, 0.0];
    } else {
        var54 = [0.0, 1.0];
    }
    var var55;
    if (input[19] <= 96.5) {
        var55 = [1.0, 0.0];
    } else {
        var55 = [0.0, 1.0];
    }
    var var56;
    if (input[20] <= 15426.5) {
        var56 = [1.0, 0.0];
    } else {
        var56 = [0.0, 1.0];
    }
    var var57;
    if (input[20] <= 15071.0) {
        var57 = [1.0, 0.0];
    } else {
        var57 = [0.0, 1.0];
    }
    var var58;
    if (input[20] <= 15071.0) {
        var58 = [1.0, 0.0];
    } else {
        var58 = [0.0, 1.0];
    }
    var var59;
    if (input[7] <= 701.5) {
        var59 = [1.0, 0.0];
    } else {
        if (input[21] <= 2.0) {
            var59 = [1.0, 0.0];
        } else {
            var59 = [0.0, 1.0];
        }
    }
    var var60;
    if (input[9] <= 0.3799999952316284) {
        var60 = [0.0, 1.0];
    } else {
        var60 = [1.0, 0.0];
    }
    var var61;
    if (input[9] <= 0.375) {
        var61 = [0.0, 1.0];
    } else {
        var61 = [1.0, 0.0];
    }
    var var62;
    if (input[12] <= 0.42499999701976776) {
        var62 = [0.0, 1.0];
    } else {
        var62 = [1.0, 0.0];
    }
    var var63;
    if (input[24] <= 5050.5) {
        var63 = [1.0, 0.0];
    } else {
        if (input[17] <= 0.5) {
            var63 = [0.0, 1.0];
        } else {
            var63 = [1.0, 0.0];
        }
    }
    var var64;
    if (input[1] <= 0.14035000279545784) {
        var64 = [0.0, 1.0];
    } else {
        var64 = [1.0, 0.0];
    }
    var var65;
    if (input[23] <= 0.5) {
        if (input[19] <= 96.5) {
            var65 = [1.0, 0.0];
        } else {
            if (input[3] <= 35.5) {
                var65 = [1.0, 0.0];
            } else {
                var65 = [0.0, 1.0];
            }
        }
    } else {
        var65 = [0.0, 1.0];
    }
    var var66;
    if (input[20] <= 13087.5) {
        var66 = [1.0, 0.0];
    } else {
        var66 = [0.0, 1.0];
    }
    var var67;
    if (input[21] <= 2.0) {
        var67 = [1.0, 0.0];
    } else {
        var67 = [0.0, 1.0];
    }
    var var68;
    if (input[19] <= 96.0) {
        var68 = [1.0, 0.0];
    } else {
        var68 = [0.0, 1.0];
    }
    var var69;
    if (input[9] <= 0.375) {
        var69 = [0.0, 1.0];
    } else {
        var69 = [1.0, 0.0];
    }
    var var70;
    if (input[6] <= 719.0) {
        if (input[20] <= 34720.5) {
            var70 = [1.0, 0.0];
        } else {
            var70 = [0.0, 1.0];
        }
    } else {
        var70 = [0.0, 1.0];
    }
    var var71;
    if (input[7] <= 707.5) {
        var71 = [1.0, 0.0];
    } else {
        var71 = [0.0, 1.0];
    }
    var var72;
    if (input[13] <= 0.5) {
        if (input[19] <= 90.5) {
            var72 = [1.0, 0.0];
        } else {
            if (input[3] <= 35.5) {
                var72 = [1.0, 0.0];
            } else {
                var72 = [0.0, 1.0];
            }
        }
    } else {
        var72 = [1.0, 0.0];
    }
    var var73;
    if (input[21] <= 1.5) {
        if (input[1] <= 0.1425500027835369) {
            var73 = [0.0, 1.0];
        } else {
            var73 = [1.0, 0.0];
        }
    } else {
        var73 = [0.0, 1.0];
    }
    var var74;
    if (input[7] <= 701.5) {
        var74 = [1.0, 0.0];
    } else {
        var74 = [0.0, 1.0];
    }
    var var75;
    if (input[1] <= 0.15755000337958336) {
        var75 = [0.0, 1.0];
    } else {
        var75 = [1.0, 0.0];
    }
    var var76;
    if (input[1] <= 0.1397000029683113) {
        var76 = [0.0, 1.0];
    } else {
        var76 = [1.0, 0.0];
    }
    var var77;
    if (input[24] <= 5157.0) {
        var77 = [1.0, 0.0];
    } else {
        if (input[20] <= 13087.5) {
            var77 = [1.0, 0.0];
        } else {
            var77 = [0.0, 1.0];
        }
    }
    var var78;
    if (input[20] <= 15426.5) {
        var78 = [1.0, 0.0];
    } else {
        var78 = [0.0, 1.0];
    }
    var var79;
    if (input[9] <= 0.375) {
        var79 = [0.0, 1.0];
    } else {
        var79 = [1.0, 0.0];
    }
    var var80;
    if (input[24] <= 5163.5) {
        var80 = [1.0, 0.0];
    } else {
        if (input[27] <= 5.620867967605591) {
            var80 = [0.0, 1.0];
        } else {
            var80 = [1.0, 0.0];
        }
    }
    var var81;
    if (input[6] <= 717.5) {
        var81 = [1.0, 0.0];
    } else {
        var81 = [0.0, 1.0];
    }
    var var82;
    if (input[1] <= 0.1356000006198883) {
        var82 = [0.0, 1.0];
    } else {
        var82 = [1.0, 0.0];
    }
    var var83;
    if (input[20] <= 15071.0) {
        var83 = [1.0, 0.0];
    } else {
        var83 = [0.0, 1.0];
    }
    var var84;
    if (input[7] <= 708.0) {
        var84 = [1.0, 0.0];
    } else {
        var84 = [0.0, 1.0];
    }
    var var85;
    if (input[12] <= 0.4650000184774399) {
        var85 = [0.0, 1.0];
    } else {
        var85 = [1.0, 0.0];
    }
    var var86;
    if (input[20] <= 19201.0) {
        var86 = [1.0, 0.0];
    } else {
        var86 = [0.0, 1.0];
    }
    var var87;
    if (input[19] <= 96.5) {
        var87 = [1.0, 0.0];
    } else {
        var87 = [0.0, 1.0];
    }
    var var88;
    if (input[11] <= 5194.5) {
        var88 = [0.0, 1.0];
    } else {
        if (input[20] <= 13087.5) {
            var88 = [1.0, 0.0];
        } else {
            var88 = [0.0, 1.0];
        }
    }
    var var89;
    if (input[15] <= 0.5) {
        if (input[8] <= 726.5) {
            var89 = [1.0, 0.0];
        } else {
            var89 = [0.0, 1.0];
        }
    } else {
        var89 = [1.0, 0.0];
    }
    var var90;
    if (input[17] <= 0.5) {
        var90 = [0.0, 1.0];
    } else {
        var90 = [1.0, 0.0];
    }
    var var91;
    if (input[20] <= 16160.5) {
        var91 = [1.0, 0.0];
    } else {
        var91 = [0.0, 1.0];
    }
    var var92;
    if (input[7] <= 707.5) {
        var92 = [1.0, 0.0];
    } else {
        var92 = [0.0, 1.0];
    }
    var var93;
    if (input[12] <= 0.42499999701976776) {
        var93 = [0.0, 1.0];
    } else {
        var93 = [1.0, 0.0];
    }
    var var94;
    if (input[12] <= 0.4650000184774399) {
        var94 = [0.0, 1.0];
    } else {
        var94 = [1.0, 0.0];
    }
    var var95;
    if (input[8] <= 727.0) {
        var95 = [1.0, 0.0];
    } else {
        var95 = [0.0, 1.0];
    }
    var var96;
    if (input[24] <= 4997.5) {
        var96 = [1.0, 0.0];
    } else {
        var96 = [0.0, 1.0];
    }
    var var97;
    if (input[7] <= 683.5) {
        var97 = [1.0, 0.0];
    } else {
        var97 = [0.0, 1.0];
    }
    var var98;
    if (input[7] <= 701.5) {
        var98 = [1.0, 0.0];
    } else {
        if (input[17] <= 1.0) {
            var98 = [0.0, 1.0];
        } else {
            var98 = [1.0, 0.0];
        }
    }
    var var99;
    if (input[24] <= 5157.0) {
        var99 = [1.0, 0.0];
    } else {
        if (input[21] <= 2.0) {
            var99 = [1.0, 0.0];
        } else {
            var99 = [0.0, 1.0];
        }
    }
    return mulVectorNumber(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(var0, var1), var2), var3), var4), var5), var6), var7), var8), var9), var10), var11), var12), var13), var14), var15), var16), var17), var18), var19), var20), var21), var22), var23), var24), var25), var26), var27), var28), var29), var30), var31), var32), var33), var34), var35), var36), var37), var38), var39), var40), var41), var42), var43), var44), var45), var46), var47), var48), var49), var50), var51), var52), var53), var54), var55), var56), var57), var58), var59), var60), var61), var62), var63), var64), var65), var66), var67), var68), var69), var70), var71), var72), var73), var74), var75), var76), var77), var78), var79), var80), var81), var82), var83), var84), var85), var86), var87), var88), var89), var90), var91), var92), var93), var94), var95), var96), var97), var98), var99), 0.01);
}
function addVectors(v1, v2) {
    var result = new Array(v1.length);
    for (var i = 0; i < v1.length; i++) {
        result[i] = v1[i] + v2[i];
    }
    return result;
}
function mulVectorNumber(v1, num) {
    var result = new Array(v1.length);
    for (var i = 0; i < v1.length; i++) {
        result[i] = v1[i] * num;
    }
    return result;
}


function scoreModel2(input) {
    var var0;
    if (input[13] <= 0.5) {
        if (input[20] <= 13087.5) {
            var0 = [1.0, 0.0];
        } else {
            var0 = [0.0, 1.0];
        }
    } else {
        var0 = [1.0, 0.0];
    }
    var var1;
    if (input[7] <= 701.5) {
        var1 = [1.0, 0.0];
    } else {
        var1 = [0.0, 1.0];
    }
    var var2;
    if (input[7] <= 704.0) {
        var2 = [1.0, 0.0];
    } else {
        var2 = [0.0, 1.0];
    }
    var var3;
    if (input[21] <= 2.5) {
        var3 = [1.0, 0.0];
    } else {
        var3 = [0.0, 1.0];
    }
    var var4;
    if (input[9] <= 0.375) {
        var4 = [0.0, 1.0];
    } else {
        var4 = [1.0, 0.0];
    }
    var var5;
    if (input[8] <= 720.5) {
        var5 = [1.0, 0.0];
    } else {
        if (input[24] <= 4773.0) {
            var5 = [1.0, 0.0];
        } else {
            var5 = [0.0, 1.0];
        }
    }
    var var6;
    if (input[1] <= 0.13625000044703484) {
        var6 = [0.0, 1.0];
    } else {
        var6 = [1.0, 0.0];
    }
    var var7;
    if (input[12] <= 0.42499999701976776) {
        var7 = [0.0, 1.0];
    } else {
        var7 = [1.0, 0.0];
    }
    var var8;
    if (input[1] <= 0.13455000147223473) {
        var8 = [0.0, 1.0];
    } else {
        var8 = [1.0, 0.0];
    }
    var var9;
    if (input[19] <= 96.5) {
        var9 = [1.0, 0.0];
    } else {
        if (input[21] <= 2.5) {
            var9 = [1.0, 0.0];
        } else {
            var9 = [0.0, 1.0];
        }
    }
    var var10;
    if (input[8] <= 726.5) {
        var10 = [1.0, 0.0];
    } else {
        var10 = [0.0, 1.0];
    }
    var var11;
    if (input[7] <= 707.5) {
        if (input[27] <= 3.4389641284942627) {
            var11 = [0.0, 1.0];
        } else {
            var11 = [1.0, 0.0];
        }
    } else {
        var11 = [0.0, 1.0];
    }
    var var12;
    if (input[8] <= 721.5) {
        var12 = [1.0, 0.0];
    } else {
        var12 = [0.0, 1.0];
    }
    var var13;
    if (input[9] <= 0.3799999952316284) {
        var13 = [0.0, 1.0];
    } else {
        var13 = [1.0, 0.0];
    }
    var var14;
    if (input[27] <= 3.43271803855896) {
        if (input[21] <= 2.0) {
            var14 = [1.0, 0.0];
        } else {
            var14 = [0.0, 1.0];
        }
    } else {
        if (input[6] <= 724.0) {
            var14 = [1.0, 0.0];
        } else {
            var14 = [0.0, 1.0];
        }
    }
    var var15;
    if (input[8] <= 720.5) {
        var15 = [1.0, 0.0];
    } else {
        var15 = [0.0, 1.0];
    }
    var var16;
    if (input[21] <= 1.5) {
        var16 = [1.0, 0.0];
    } else {
        var16 = [0.0, 1.0];
    }
    var var17;
    if (input[1] <= 0.15755000337958336) {
        var17 = [0.0, 1.0];
    } else {
        var17 = [1.0, 0.0];
    }
    var var18;
    if (input[7] <= 707.5) {
        var18 = [1.0, 0.0];
    } else {
        var18 = [0.0, 1.0];
    }
    var var19;
    if (input[21] <= 1.5) {
        var19 = [1.0, 0.0];
    } else {
        var19 = [0.0, 1.0];
    }
    var var20;
    if (input[9] <= 0.35999999940395355) {
        var20 = [0.0, 1.0];
    } else {
        var20 = [1.0, 0.0];
    }
    var var21;
    if (input[20] <= 16516.0) {
        var21 = [1.0, 0.0];
    } else {
        var21 = [0.0, 1.0];
    }
    var var22;
    if (input[20] <= 16160.5) {
        var22 = [1.0, 0.0];
    } else {
        var22 = [0.0, 1.0];
    }
    var var23;
    if (input[1] <= 0.13625000044703484) {
        var23 = [0.0, 1.0];
    } else {
        var23 = [1.0, 0.0];
    }
    var var24;
    if (input[9] <= 0.3799999952316284) {
        var24 = [0.0, 1.0];
    } else {
        var24 = [1.0, 0.0];
    }
    var var25;
    if (input[23] <= 0.5) {
        if (input[24] <= 6455.0) {
            var25 = [1.0, 0.0];
        } else {
            var25 = [0.0, 1.0];
        }
    } else {
        var25 = [0.0, 1.0];
    }
    var var26;
    if (input[7] <= 678.5) {
        var26 = [1.0, 0.0];
    } else {
        var26 = [0.0, 1.0];
    }
    var var27;
    if (input[6] <= 711.0) {
        var27 = [1.0, 0.0];
    } else {
        var27 = [0.0, 1.0];
    }
    var var28;
    if (input[20] <= 15426.5) {
        var28 = [1.0, 0.0];
    } else {
        var28 = [0.0, 1.0];
    }
    var var29;
    if (input[20] <= 17884.0) {
        var29 = [1.0, 0.0];
    } else {
        var29 = [0.0, 1.0];
    }
    var var30;
    if (input[12] <= 0.42499999701976776) {
        var30 = [0.0, 1.0];
    } else {
        var30 = [1.0, 0.0];
    }
    var var31;
    if (input[21] <= 1.5) {
        var31 = [1.0, 0.0];
    } else {
        var31 = [0.0, 1.0];
    }
    var var32;
    if (input[1] <= 0.14035000279545784) {
        var32 = [0.0, 1.0];
    } else {
        var32 = [1.0, 0.0];
    }
    var var33;
    if (input[16] <= 3.5) {
        if (input[19] <= 96.5) {
            var33 = [1.0, 0.0];
        } else {
            var33 = [0.0, 1.0];
        }
    } else {
        var33 = [1.0, 0.0];
    }
    var var34;
    if (input[1] <= 0.14035000279545784) {
        var34 = [0.0, 1.0];
    } else {
        var34 = [1.0, 0.0];
    }
    var var35;
    if (input[20] <= 15426.5) {
        var35 = [1.0, 0.0];
    } else {
        var35 = [0.0, 1.0];
    }
    var var36;
    if (input[12] <= 0.41499999165534973) {
        var36 = [0.0, 1.0];
    } else {
        var36 = [1.0, 0.0];
    }
    var var37;
    if (input[8] <= 727.0) {
        var37 = [1.0, 0.0];
    } else {
        var37 = [0.0, 1.0];
    }
    var var38;
    if (input[20] <= 15426.5) {
        var38 = [1.0, 0.0];
    } else {
        var38 = [0.0, 1.0];
    }
    var var39;
    if (input[9] <= 0.3400000035762787) {
        var39 = [0.0, 1.0];
    } else {
        var39 = [1.0, 0.0];
    }
    var var40;
    if (input[0] <= 48.0) {
        var40 = [0.0, 1.0];
    } else {
        if (input[1] <= 0.13625000044703484) {
            var40 = [0.0, 1.0];
        } else {
            var40 = [1.0, 0.0];
        }
    }
    var var41;
    if (input[1] <= 0.13625000044703484) {
        var41 = [0.0, 1.0];
    } else {
        var41 = [1.0, 0.0];
    }
    var var42;
    if (input[9] <= 0.375) {
        var42 = [0.0, 1.0];
    } else {
        var42 = [1.0, 0.0];
    }
    var var43;
    if (input[24] <= 4997.5) {
        var43 = [1.0, 0.0];
    } else {
        var43 = [0.0, 1.0];
    }
    var var44;
    if (input[19] <= 96.5) {
        var44 = [1.0, 0.0];
    } else {
        var44 = [0.0, 1.0];
    }
    var var45;
    if (input[12] <= 0.4650000184774399) {
        var45 = [0.0, 1.0];
    } else {
        var45 = [1.0, 0.0];
    }
    var var46;
    if (input[1] <= 0.14035000279545784) {
        var46 = [0.0, 1.0];
    } else {
        var46 = [1.0, 0.0];
    }
    var var47;
    if (input[19] <= 96.5) {
        var47 = [1.0, 0.0];
    } else {
        if (input[12] <= 0.42499999701976776) {
            var47 = [0.0, 1.0];
        } else {
            var47 = [1.0, 0.0];
        }
    }
    var var48;
    if (input[6] <= 719.0) {
        if (input[24] <= 6455.0) {
            var48 = [1.0, 0.0];
        } else {
            var48 = [0.0, 1.0];
        }
    } else {
        var48 = [0.0, 1.0];
    }
    var var49;
    if (input[12] <= 0.42499999701976776) {
        var49 = [0.0, 1.0];
    } else {
        var49 = [1.0, 0.0];
    }
    var var50;
    if (input[8] <= 707.5) {
        var50 = [1.0, 0.0];
    } else {
        var50 = [0.0, 1.0];
    }
    var var51;
    if (input[17] <= 0.5) {
        if (input[24] <= 4231.5) {
            var51 = [1.0, 0.0];
        } else {
            var51 = [0.0, 1.0];
        }
    } else {
        var51 = [1.0, 0.0];
    }
    var var52;
    if (input[20] <= 15071.0) {
        var52 = [1.0, 0.0];
    } else {
        var52 = [0.0, 1.0];
    }
    var var53;
    if (input[16] <= 4.0) {
        if (input[7] <= 681.5) {
            var53 = [1.0, 0.0];
        } else {
            var53 = [0.0, 1.0];
        }
    } else {
        var53 = [1.0, 0.0];
    }
    var var54;
    if (input[21] <= 1.5) {
        var54 = [1.0, 0.0];
    } else {
        var54 = [0.0, 1.0];
    }
    var var55;
    if (input[16] <= 3.5) {
        if (input[20] <= 16160.5) {
            var55 = [1.0, 0.0];
        } else {
            var55 = [0.0, 1.0];
        }
    } else {
        var55 = [1.0, 0.0];
    }
    var var56;
    if (input[21] <= 1.5) {
        if (input[1] <= 0.1253500021994114) {
            var56 = [0.0, 1.0];
        } else {
            var56 = [1.0, 0.0];
        }
    } else {
        var56 = [0.0, 1.0];
    }
    var var57;
    if (input[11] <= 5123.0) {
        var57 = [0.0, 1.0];
    } else {
        if (input[1] <= 0.11960000172257423) {
            var57 = [0.0, 1.0];
        } else {
            var57 = [1.0, 0.0];
        }
    }
    var var58;
    if (input[16] <= 3.5) {
        if (input[1] <= 0.13625000044703484) {
            var58 = [0.0, 1.0];
        } else {
            var58 = [1.0, 0.0];
        }
    } else {
        var58 = [1.0, 0.0];
    }
    var var59;
    if (input[12] <= 0.42499999701976776) {
        var59 = [0.0, 1.0];
    } else {
        var59 = [1.0, 0.0];
    }
    var var60;
    if (input[24] <= 4997.5) {
        var60 = [1.0, 0.0];
    } else {
        if (input[21] <= 1.5) {
            var60 = [1.0, 0.0];
        } else {
            var60 = [0.0, 1.0];
        }
    }
    var var61;
    if (input[9] <= 0.3799999952316284) {
        var61 = [0.0, 1.0];
    } else {
        var61 = [1.0, 0.0];
    }
    var var62;
    if (input[17] <= 0.5) {
        if (input[1] <= 0.17375000193715096) {
            var62 = [0.0, 1.0];
        } else {
            var62 = [1.0, 0.0];
        }
    } else {
        var62 = [1.0, 0.0];
    }
    var var63;
    if (input[9] <= 0.375) {
        var63 = [0.0, 1.0];
    } else {
        var63 = [1.0, 0.0];
    }
    var var64;
    if (input[20] <= 15426.5) {
        var64 = [1.0, 0.0];
    } else {
        var64 = [0.0, 1.0];
    }
    var var65;
    if (input[8] <= 726.5) {
        if (input[7] <= 678.5) {
            var65 = [1.0, 0.0];
        } else {
            if (input[11] <= 3587.5) {
                var65 = [0.0, 1.0];
            } else {
                var65 = [1.0, 0.0];
            }
        }
    } else {
        var65 = [0.0, 1.0];
    }
    var var66;
    if (input[24] <= 5157.0) {
        var66 = [1.0, 0.0];
    } else {
        var66 = [0.0, 1.0];
    }
    var var67;
    if (input[13] <= 0.5) {
        if (input[7] <= 707.5) {
            if (input[12] <= 0.41499999165534973) {
                var67 = [0.0, 1.0];
            } else {
                var67 = [1.0, 0.0];
            }
        } else {
            var67 = [0.0, 1.0];
        }
    } else {
        var67 = [1.0, 0.0];
    }
    var var68;
    if (input[21] <= 1.5) {
        if (input[13] <= 0.5) {
            if (input[9] <= 0.3100000023841858) {
                var68 = [0.0, 1.0];
            } else {
                var68 = [1.0, 0.0];
            }
        } else {
            var68 = [1.0, 0.0];
        }
    } else {
        var68 = [0.0, 1.0];
    }
    var var69;
    if (input[8] <= 702.0) {
        var69 = [1.0, 0.0];
    } else {
        var69 = [0.0, 1.0];
    }
    var var70;
    if (input[12] <= 0.4749999940395355) {
        var70 = [0.0, 1.0];
    } else {
        var70 = [1.0, 0.0];
    }
    var var71;
    if (input[6] <= 717.0) {
        var71 = [1.0, 0.0];
    } else {
        var71 = [0.0, 1.0];
    }
    var var72;
    if (input[0] <= 48.0) {
        var72 = [0.0, 1.0];
    } else {
        if (input[9] <= 0.35500000417232513) {
            var72 = [0.0, 1.0];
        } else {
            var72 = [1.0, 0.0];
        }
    }
    var var73;
    if (input[19] <= 96.5) {
        var73 = [1.0, 0.0];
    } else {
        if (input[20] <= 15426.5) {
            var73 = [1.0, 0.0];
        } else {
            var73 = [0.0, 1.0];
        }
    }
    var var74;
    if (input[1] <= 0.12150000035762787) {
        var74 = [0.0, 1.0];
    } else {
        var74 = [1.0, 0.0];
    }
    var var75;
    if (input[19] <= 96.5) {
        var75 = [1.0, 0.0];
    } else {
        var75 = [0.0, 1.0];
    }
    var var76;
    if (input[12] <= 0.4650000184774399) {
        var76 = [0.0, 1.0];
    } else {
        var76 = [1.0, 0.0];
    }
    var var77;
    if (input[12] <= 0.42499999701976776) {
        var77 = [0.0, 1.0];
    } else {
        var77 = [1.0, 0.0];
    }
    var var78;
    if (input[27] <= 3.5190054178237915) {
        if (input[9] <= 0.5450000017881393) {
            var78 = [0.0, 1.0];
        } else {
            var78 = [1.0, 0.0];
        }
    } else {
        if (input[1] <= 0.15485000237822533) {
            var78 = [0.0, 1.0];
        } else {
            var78 = [1.0, 0.0];
        }
    }
    var var79;
    if (input[17] <= 1.0) {
        if (input[27] <= 7.4166059494018555) {
            var79 = [0.0, 1.0];
        } else {
            var79 = [1.0, 0.0];
        }
    } else {
        var79 = [1.0, 0.0];
    }
    var var80;
    if (input[6] <= 711.0) {
        var80 = [1.0, 0.0];
    } else {
        var80 = [0.0, 1.0];
    }
    var var81;
    if (input[19] <= 96.0) {
        var81 = [1.0, 0.0];
    } else {
        if (input[24] <= 4391.0) {
            var81 = [1.0, 0.0];
        } else {
            var81 = [0.0, 1.0];
        }
    }
    var var82;
    if (input[20] <= 16516.0) {
        var82 = [1.0, 0.0];
    } else {
        var82 = [0.0, 1.0];
    }
    var var83;
    if (input[14] <= 602.0) {
        if (input[7] <= 707.5) {
            if (input[1] <= 0.10700000263750553) {
                var83 = [0.0, 1.0];
            } else {
                var83 = [1.0, 0.0];
            }
        } else {
            var83 = [0.0, 1.0];
        }
    } else {
        var83 = [1.0, 0.0];
    }
    var var84;
    if (input[6] <= 711.0) {
        var84 = [1.0, 0.0];
    } else {
        var84 = [0.0, 1.0];
    }
    var var85;
    if (input[11] <= 5054.0) {
        var85 = [0.0, 1.0];
    } else {
        if (input[24] <= 5050.5) {
            var85 = [1.0, 0.0];
        } else {
            var85 = [0.0, 1.0];
        }
    }
    var var86;
    if (input[23] <= 0.5) {
        if (input[24] <= 6455.0) {
            if (input[19] <= 96.5) {
                var86 = [1.0, 0.0];
            } else {
                var86 = [0.5, 0.5];
            }
        } else {
            var86 = [0.0, 1.0];
        }
    } else {
        var86 = [0.0, 1.0];
    }
    var var87;
    if (input[8] <= 727.0) {
        var87 = [1.0, 0.0];
    } else {
        var87 = [0.0, 1.0];
    }
    var var88;
    if (input[23] <= 0.5) {
        if (input[8] <= 731.0) {
            var88 = [1.0, 0.0];
        } else {
            var88 = [0.0, 1.0];
        }
    } else {
        var88 = [0.0, 1.0];
    }
    var var89;
    if (input[26] <= 713.3300170898438) {
        if (input[28] <= 0.07354458048939705) {
            if (input[19] <= 91.16327667236328) {
                var89 = [1.0, 0.0];
            } else {
                var89 = [0.0, 1.0];
            }
        } else {
            var89 = [1.0, 0.0];
        }
    } else {
        var89 = [0.0, 1.0];
    }
    var var90;
    if (input[24] <= 4997.5) {
        var90 = [1.0, 0.0];
    } else {
        var90 = [0.0, 1.0];
    }
    var var91;
    if (input[1] <= 0.13455000147223473) {
        var91 = [0.0, 1.0];
    } else {
        var91 = [1.0, 0.0];
    }
    var var92;
    if (input[9] <= 0.375) {
        var92 = [0.0, 1.0];
    } else {
        var92 = [1.0, 0.0];
    }
    var var93;
    if (input[1] <= 0.1397000029683113) {
        var93 = [0.0, 1.0];
    } else {
        var93 = [1.0, 0.0];
    }
    var var94;
    if (input[20] <= 15426.5) {
        var94 = [1.0, 0.0];
    } else {
        var94 = [0.0, 1.0];
    }
    var var95;
    if (input[6] <= 711.0) {
        var95 = [1.0, 0.0];
    } else {
        var95 = [0.0, 1.0];
    }
    var var96;
    if (input[9] <= 0.3799999952316284) {
        var96 = [0.0, 1.0];
    } else {
        var96 = [1.0, 0.0];
    }
    var var97;
    if (input[19] <= 96.5) {
        var97 = [1.0, 0.0];
    } else {
        if (input[7] <= 676.5) {
            var97 = [1.0, 0.0];
        } else {
            var97 = [0.0, 1.0];
        }
    }
    var var98;
    if (input[12] <= 0.48999999463558197) {
        var98 = [0.0, 1.0];
    } else {
        var98 = [1.0, 0.0];
    }
    var var99;
    if (input[27] <= 5.112950325012207) {
        if (input[9] <= 0.42000000178813934) {
            var99 = [0.0, 1.0];
        } else {
            var99 = [1.0, 0.0];
        }
    } else {
        if (input[17] <= 1.0) {
            var99 = [0.0, 1.0];
        } else {
            var99 = [1.0, 0.0];
        }
    }
    return mulVectorNumber(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(var0, var1), var2), var3), var4), var5), var6), var7), var8), var9), var10), var11), var12), var13), var14), var15), var16), var17), var18), var19), var20), var21), var22), var23), var24), var25), var26), var27), var28), var29), var30), var31), var32), var33), var34), var35), var36), var37), var38), var39), var40), var41), var42), var43), var44), var45), var46), var47), var48), var49), var50), var51), var52), var53), var54), var55), var56), var57), var58), var59), var60), var61), var62), var63), var64), var65), var66), var67), var68), var69), var70), var71), var72), var73), var74), var75), var76), var77), var78), var79), var80), var81), var82), var83), var84), var85), var86), var87), var88), var89), var90), var91), var92), var93), var94), var95), var96), var97), var98), var99), 0.01);
}
function addVectors(v1, v2) {
    var result = new Array(v1.length);
    for (var i = 0; i < v1.length; i++) {
        result[i] = v1[i] + v2[i];
    }
    return result;
}
function mulVectorNumber(v1, num) {
    var result = new Array(v1.length);
    for (var i = 0; i < v1.length; i++) {
        result[i] = v1[i] * num;
    }
    return result;
}


function scoreModel3(input) {
    var var0;
    if (input[12] <= 0.41499999165534973) {
        var0 = [0.0, 1.0];
    } else {
        var0 = [1.0, 0.0];
    }
    var var1;
    if (input[11] <= 5015.5) {
        var1 = [0.0, 1.0];
    } else {
        if (input[8] <= 733.5) {
            var1 = [1.0, 0.0];
        } else {
            var1 = [0.0, 1.0];
        }
    }
    var var2;
    if (input[24] <= 4997.5) {
        var2 = [1.0, 0.0];
    } else {
        var2 = [0.0, 1.0];
    }
    var var3;
    if (input[24] <= 5163.5) {
        var3 = [1.0, 0.0];
    } else {
        var3 = [0.0, 1.0];
    }
    var var4;
    if (input[8] <= 726.5) {
        var4 = [1.0, 0.0];
    } else {
        var4 = [0.0, 1.0];
    }
    var var5;
    if (input[9] <= 0.375) {
        var5 = [0.0, 1.0];
    } else {
        var5 = [1.0, 0.0];
    }
    var var6;
    if (input[16] <= 3.5) {
        if (input[1] <= 0.13625000044703484) {
            var6 = [0.0, 1.0];
        } else {
            var6 = [1.0, 0.0];
        }
    } else {
        var6 = [1.0, 0.0];
    }
    var var7;
    if (input[12] <= 0.42499999701976776) {
        var7 = [0.0, 1.0];
    } else {
        var7 = [1.0, 0.0];
    }
    var var8;
    if (input[20] <= 15426.5) {
        var8 = [1.0, 0.0];
    } else {
        var8 = [0.0, 1.0];
    }
    var var9;
    if (input[19] <= 96.0) {
        var9 = [1.0, 0.0];
    } else {
        var9 = [0.0, 1.0];
    }
    var var10;
    if (input[21] <= 2.5) {
        var10 = [1.0, 0.0];
    } else {
        var10 = [0.0, 1.0];
    }
    var var11;
    if (input[6] <= 721.5) {
        if (input[19] <= 96.5) {
            var11 = [1.0, 0.0];
        } else {
            var11 = [0.0, 1.0];
        }
    } else {
        var11 = [0.0, 1.0];
    }
    var var12;
    if (input[9] <= 0.41499999165534973) {
        var12 = [0.0, 1.0];
    } else {
        var12 = [1.0, 0.0];
    }
    var var13;
    if (input[17] <= 0.5) {
        if (input[11] <= 10437.0) {
            var13 = [0.0, 1.0];
        } else {
            var13 = [1.0, 0.0];
        }
    } else {
        var13 = [1.0, 0.0];
    }
    var var14;
    if (input[16] <= 3.5) {
        if (input[1] <= 0.13625000044703484) {
            var14 = [0.0, 1.0];
        } else {
            var14 = [1.0, 0.0];
        }
    } else {
        var14 = [1.0, 0.0];
    }
    var var15;
    if (input[9] <= 0.42000000178813934) {
        var15 = [0.0, 1.0];
    } else {
        var15 = [1.0, 0.0];
    }
    var var16;
    if (input[0] <= 48.0) {
        var16 = [0.0, 1.0];
    } else {
        if (input[1] <= 0.1262499988079071) {
            var16 = [0.0, 1.0];
        } else {
            var16 = [1.0, 0.0];
        }
    }
    var var17;
    if (input[7] <= 701.5) {
        var17 = [1.0, 0.0];
    } else {
        var17 = [0.0, 1.0];
    }
    var var18;
    if (input[21] <= 2.0) {
        if (input[23] <= 1.0) {
            var18 = [1.0, 0.0];
        } else {
            var18 = [0.0, 1.0];
        }
    } else {
        var18 = [0.0, 1.0];
    }
    var var19;
    if (input[6] <= 711.5) {
        var19 = [1.0, 0.0];
    } else {
        var19 = [0.0, 1.0];
    }
    var var20;
    if (input[17] <= 0.5) {
        var20 = [0.0, 1.0];
    } else {
        var20 = [1.0, 0.0];
    }
    var var21;
    if (input[21] <= 2.0) {
        var21 = [1.0, 0.0];
    } else {
        var21 = [0.0, 1.0];
    }
    var var22;
    if (input[20] <= 16160.5) {
        var22 = [1.0, 0.0];
    } else {
        var22 = [0.0, 1.0];
    }
    var var23;
    if (input[8] <= 720.5) {
        var23 = [1.0, 0.0];
    } else {
        if (input[20] <= 12978.5) {
            var23 = [1.0, 0.0];
        } else {
            var23 = [0.0, 1.0];
        }
    }
    var var24;
    if (input[27] <= 3.5190054178237915) {
        var24 = [0.0, 1.0];
    } else {
        if (input[7] <= 720.5) {
            var24 = [1.0, 0.0];
        } else {
            var24 = [0.0, 1.0];
        }
    }
    var var25;
    if (input[26] <= 765.5549926757812) {
        if (input[11] <= 5123.0) {
            var25 = [0.0, 1.0];
        } else {
            var25 = [1.0, 0.0];
        }
    } else {
        var25 = [0.0, 1.0];
    }
    var var26;
    if (input[20] <= 15426.5) {
        var26 = [1.0, 0.0];
    } else {
        var26 = [0.0, 1.0];
    }
    var var27;
    if (input[9] <= 0.375) {
        var27 = [0.0, 1.0];
    } else {
        var27 = [1.0, 0.0];
    }
    var var28;
    if (input[6] <= 688.0) {
        var28 = [1.0, 0.0];
    } else {
        if (input[1] <= 0.17464999854564667) {
            var28 = [0.0, 1.0];
        } else {
            var28 = [1.0, 0.0];
        }
    }
    var var29;
    if (input[21] <= 1.5) {
        if (input[8] <= 768.5) {
            var29 = [1.0, 0.0];
        } else {
            var29 = [0.0, 1.0];
        }
    } else {
        var29 = [0.0, 1.0];
    }
    var var30;
    if (input[20] <= 15426.5) {
        var30 = [1.0, 0.0];
    } else {
        var30 = [0.0, 1.0];
    }
    var var31;
    if (input[1] <= 0.1356000006198883) {
        var31 = [0.0, 1.0];
    } else {
        var31 = [1.0, 0.0];
    }
    var var32;
    if (input[12] <= 0.4749999940395355) {
        var32 = [0.0, 1.0];
    } else {
        var32 = [1.0, 0.0];
    }
    var var33;
    if (input[7] <= 707.5) {
        var33 = [1.0, 0.0];
    } else {
        var33 = [0.0, 1.0];
    }
    var var34;
    if (input[8] <= 726.5) {
        if (input[1] <= 0.10290000028908253) {
            var34 = [0.0, 1.0];
        } else {
            var34 = [1.0, 0.0];
        }
    } else {
        var34 = [0.0, 1.0];
    }
    var var35;
    if (input[12] <= 0.42499999701976776) {
        var35 = [0.0, 1.0];
    } else {
        var35 = [1.0, 0.0];
    }
    var var36;
    if (input[20] <= 13087.5) {
        var36 = [1.0, 0.0];
    } else {
        var36 = [0.0, 1.0];
    }
    var var37;
    if (input[20] <= 15426.5) {
        var37 = [1.0, 0.0];
    } else {
        var37 = [0.0, 1.0];
    }
    var var38;
    if (input[12] <= 0.4650000184774399) {
        var38 = [0.0, 1.0];
    } else {
        var38 = [1.0, 0.0];
    }
    var var39;
    if (input[1] <= 0.13455000147223473) {
        var39 = [0.0, 1.0];
    } else {
        var39 = [1.0, 0.0];
    }
    var var40;
    if (input[15] <= 0.5) {
        if (input[24] <= 4997.5) {
            var40 = [1.0, 0.0];
        } else {
            var40 = [0.0, 1.0];
        }
    } else {
        var40 = [1.0, 0.0];
    }
    var var41;
    if (input[6] <= 692.5) {
        var41 = [1.0, 0.0];
    } else {
        var41 = [0.0, 1.0];
    }
    var var42;
    if (input[9] <= 0.375) {
        var42 = [0.0, 1.0];
    } else {
        var42 = [1.0, 0.0];
    }
    var var43;
    if (input[1] <= 0.13625000044703484) {
        var43 = [0.0, 1.0];
    } else {
        var43 = [1.0, 0.0];
    }
    var var44;
    if (input[27] <= 3.6710221767425537) {
        var44 = [0.0, 1.0];
    } else {
        if (input[12] <= 0.4400000125169754) {
            var44 = [0.0, 1.0];
        } else {
            var44 = [1.0, 0.0];
        }
    }
    var var45;
    if (input[1] <= 0.13625000044703484) {
        var45 = [0.0, 1.0];
    } else {
        var45 = [1.0, 0.0];
    }
    var var46;
    if (input[3] <= 85.0) {
        if (input[23] <= 0.5) {
            var46 = [0.9166666666666666, 0.08333333333333333];
        } else {
            var46 = [0.0, 1.0];
        }
    } else {
        var46 = [0.0, 1.0];
    }
    var var47;
    if (input[16] <= 3.5) {
        if (input[8] <= 701.0) {
            var47 = [1.0, 0.0];
        } else {
            var47 = [0.0, 1.0];
        }
    } else {
        var47 = [1.0, 0.0];
    }
    var var48;
    if (input[12] <= 0.4650000184774399) {
        var48 = [0.0, 1.0];
    } else {
        var48 = [1.0, 0.0];
    }
    var var49;
    if (input[27] <= 3.4384783506393433) {
        var49 = [0.0, 1.0];
    } else {
        if (input[26] <= 765.5549926757812) {
            var49 = [1.0, 0.0];
        } else {
            var49 = [0.0, 1.0];
        }
    }
    return mulVectorNumber(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(addVectors(var0, var1), var2), var3), var4), var5), var6), var7), var8), var9), var10), var11), var12), var13), var14), var15), var16), var17), var18), var19), var20), var21), var22), var23), var24), var25), var26), var27), var28), var29), var30), var31), var32), var33), var34), var35), var36), var37), var38), var39), var40), var41), var42), var43), var44), var45), var46), var47), var48), var49), 0.02);
}
function addVectors(v1, v2) {
    var result = new Array(v1.length);
    for (var i = 0; i < v1.length; i++) {
        result[i] = v1[i] + v2[i];
    }
    return result;
}
function mulVectorNumber(v1, num) {
    var result = new Array(v1.length);
    for (var i = 0; i < v1.length; i++) {
        result[i] = v1[i] * num;
    }
    return result;
}


const FEATURE_NAMES = ["term", "lender_yield", "listing_category", "employment_duration", "is_homeowner", "in_group", "CreditScoreMean", "credit_score_lower", "credit_score_upper", "debt_to_income", "current_credit_lines", "revolving_balance", "bankcard_utilization", "delinquencies_7y", "amount_delinquent", "public_records", "total_inquiries", "inquiries_6m", "total_trades", "trades_never_delinquent", "available_credit", "investors", "investment_friends_amount", "recommendations", "monthly_income", "loan_amount", "monthly_payment", "LoanToIncome", "PaymentToIncome", "LenderYield_mean_by_ListingCategory", "LenderYield_mean_by_Term", "EmploymentStatus_Full-time", "EmploymentStatus_Not employed", "EmploymentStatus_Part-time", "EmploymentStatus_Self-employed", "StateCluster_1", "StateCluster_2", "StateCluster_3", "StateCluster_4", "StateCluster_5", "StateCluster_6"];
const ENSEMBLE_WEIGHTS = [1, 1, 1];

function predictEnsemble(features) {
    // Extract values matching the feature names order
    let inputVector = [];
    for (let i = 0; i < FEATURE_NAMES.length; i++) {
        inputVector.push(features[FEATURE_NAMES[i]] || 0);
    }
    
    // Get votes from models (RandomForest outputs [votes_class_0, votes_class_1])
    let votes1 = scoreModel1(inputVector);
    let votes2 = scoreModel2(inputVector);
    let votes3 = scoreModel3(inputVector);
    
    // Convert to probability
    let p1 = votes1[1] / (votes1[0] + votes1[1]);
    let p2 = votes2[1] / (votes2[0] + votes2[1]);
    let p3 = votes3[1] / (votes3[0] + votes3[1]);
    
    let w1 = ENSEMBLE_WEIGHTS[0];
    let w2 = ENSEMBLE_WEIGHTS[1];
    let w3 = ENSEMBLE_WEIGHTS[2];
    
    let finalProb = (w1 * p1 + w2 * p2 + w3 * p3) / (w1 + w2 + w3);
    
    return {
        approved: finalProb > 0.5,
        probability: finalProb
    };
}
